vrk-kpa/opendata

- ansible/roles/ckan/templates/ckan.ini.j2
- ansible/roles/ckan/vars/main.yml
- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/schemas/group.json
- modules/ytp-drupal-frontpage/ytp_frontpage.module
- Default group schema replacement
- Language translation changes (group -> category)
- Front page category fixes
> Feature category translation

- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/ckanext-sixodp_showcase.pot
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/en_GB/LC_MESSAGES/ckanext-sixodp_showcase.po
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/fi/LC_MESSAGES/ckanext-sixodp_showcase.po
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/sv/LC_MESSAGES/ckanext-sixodp_showcase.po
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/search.html
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_greeting.html
- Added greeting section to applicaton showcase view with short
information section regarding applications and how to add them to the
system.
> Added greeting section to showcase view

- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/search.html
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_greeting.html
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_item.html
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_search_input.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form_without_input.html
- modules/ytp-assets-common/gulpfile.js
- modules/ytp-assets-common/src/less/ckan/ckan.less
- modules/ytp-assets-common/src/less/common.less
- modules/ytp-assets-common/src/less/navbars.less
- modules/ytp-assets-common/src/less/variables.less
- Base styling for new applications view.
- Gulp watch task fixes.
- Added gulp watch task for styles only.
- Edited search views and added the greeting template from master.
- Dev branch related translations
> Dev styling for ckan applications view

- modules/ytp-assets-common/gulpfile.js
- modules/ytp-assets-common/package-lock.json
- modules/ytp-assets-common/package.json
- Updated gulp from version 3 to 4.
- Tweaked gulp tasks.
- Updated related packages.
- Removed unused packages.
- Added package-lock file.
> Tweak ytp-assets-common gulp

- modules/avoindata-drupal-theme/less/overrides.less
- modules/avoindata-drupal-theme/templates/block/block--avoindata-sitebranding.html.twig
- modules/avoindata-drupal-theme/templates/system/page.html.twig
- modules/ytp-assets-common/src/less/variables.less
> Header muutoksia

- modules/avoindata-drupal-hero/avoindata_hero.libraries.yml
- modules/avoindata-drupal-hero/js/avoindata-hero.js
- modules/avoindata-drupal-hero/src/Plugin/Form/HeroForm.php
- modules/avoindata-drupal-hero/templates/avoindata_hero_form.html.twig
- Removed data count fetches from avoindata-hero.js.
- Added similar fetches to HeroForm build function.
- Removed polyfills as they are no longer needed.
> Moved hero module data fetches from client-side

- ansible/roles/drupal/tasks/main.yml
- drupal8/composer.json
- modules/avoindata-drupal-header/avoindata_header.links.menu.yml
- modules/ytp-assets-common/src/less/navbars.less
- Fix menu links
- Add menu links for applications, login and register
- Add fontawesome icon support for menus
- Menu styling
> Avoindata drupal header

- modules/avoindata-drupal-theme/config/install/block.block.avoindata_footer.yml
- modules/avoindata-drupal-theme/config/install/block.block.avoindata_header.yml
- Remove unnecessary path restrictions from showing header/footer in drupal
> Show header/footer on all drupal pages

- ansible/roles/ckan/files/override-requirements.txt
- modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py
- Added support for mapping harvested dataset groups into zero or more groups (ignoring groups, changing groups or subdividing groups).
- Additionally added some error logging to ease finding harvesting error causes from log output.
> Added group mapping support to sixodp_harvester

- ansible/roles/ckan/templates/apache2.j2
- ansible/roles/ckan/templates/ckan.ini.j2
- ansible/single-server.yml
- ansible/vars/common.yml
- ansible/vars/environment-specific/vagrant.yml
- modules/ckanext-ytp_main/ckanext/ytp/templates/page.html
Environment specific vars can override common vars.
> Add Debug information to ckan in vagrant

- .gitmodules
- ansible/roles/ckan/templates/ckan.ini.j2
- New ckanext-disqus fork
- Email notification support for comments
> Added e-mail notification support to disqus

- modules/avoindata-drupal-articles/src/Controller/ArticlesController.php
- modules/avoindata-drupal-events/src/Controller/EventsController.php
- Both searches now combine results from body and title searchs.
(Requires two queries currently. This can probably be improved)
- Events are now sorted by the field_start_date (start date of the
event) instead of the creation date.
> Improved Articles and Events page searches

- modules/avoindata-drupal-header/avoindata_header.links.menu.yml
- modules/avoindata-drupal-header/avoindata_header.routing.yml
- modules/avoindata-drupal-header/src/Controller/HeaderController.php
- Added profile link to header that redirects authenticated user to ckan
profile
> AV 118 Add ckan profile link to drupal header

- ansible/roles/drupal/tasks/main.yml
- Added a task in ansible to reimport theme's config/install
> Reimport theme configuration files in deploy

- modules/avoindata-drupal-servicemessage/src/Plugin/Block/ServicemessageBlock.php
- Added cache settings to block. Cache is now cleared when any node
changes in drupal.
> AV 139 added cache settings to service messages

- ansible/roles/drupal/tasks/main.yml
- drupal8/composer.json
- modules/avoindata-drupal-appfeed/templates/avoindata_appfeed_block.html.twig
- modules/avoindata-drupal-events/templates/avoindata_events_block.html.twig
- modules/avoindata-drupal-newsfeed/templates/avoindata_newsfeed_block.html.twig
- Fixed twig dateformat bug that was caused by wrong input to the
format_date function.
- Also removed the twig_extensions extension as it seemed to cause some
errors at controller level.
> AV 143 Twig dateformat bug

- modules/ckanext-ytp_request/ckanext/ytp_request/templates/request/list.html
- modules/ckanext-ytp_request/ckanext/ytp_request/templates/request/mylist.html
- Fixed breadcrumbs for request "list" and "mylist" pages
(breadcrumb_content block was missing from these).
> AV 132 CKAN request breadcrumbs fix

- modules/ckanext-ytp_request/ckanext/ytp_request/logic/action/get.py
- modules/ckanext-ytp_request/ckanext/ytp_request/templates/request/list.html
- Added email field to member request view.
> AV 123 Added email to member request list

- .gitmodules
- ansible/roles/ckan/vars/main.yml
- ansible/roles/drupal/tasks/main.yml
- modules/ckanext-ytp_main/ckanext/ytp/helpers.py
- modules/ckanext-ytp_main/ckanext/ytp/logic.py
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_info.html
Forked QA, added jobs support and fixed flake8.
> CKAN 2.8 support for ckanext QA

- ansible/roles/drupal/tasks/main.yml
- drupal8/composer.json
Two commit for adding and removing twig extensions
> Fix removal of twig extensions

- ansible/roles/ckan/templates/ckan.ini.j2
- ansible/roles/ckan/vars/main.yml
- modules/ckanext-ytp_main/ckanext/ytp/commands.py
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/schemas/organization.json
- modules/ckanext-ytp_main/setup.py
- Added organization schema
- Implemented organization migration tool
> AV-112 scheming organizations

- ansible/roles/drupal/tasks/main.yml
- Fixed the problem with language import (ansible was using vagrant
path).
> AV-153 Ansible language translation import fix

- modules/ckanext-ytp_main/ckanext/ytp/auth.py
- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/schemas/organization.json
- modules/ckanext-ytp_main/ckanext/ytp/translations.py
- Updated ckanext-scheming
- Added personal_datasets feature to organization schema
- Added package_update validator with personal_datasets handling
- Translations
> AV-125: Personal datasets feature for organizations

- ansible/roles/drupal/tasks/main.yml
- Added ansible task that removes the composer.lock file if it already
exists.
> AV-129 Fix composer lock issues

- modules/ckanext-ytp_main/ckanext/ytp/commands.py
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/setup.py
* Added functionality for adding new users to all groups as editors automatically
* Added click command to add existing users to all groups as editors
> Add users to groups

- ansible/roles/drupal/tasks/main.yml
- ansible/roles/drupal/templates/drupal_site_config/disqus.settings.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/smtp.settings.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/user.settings.yml.j2
- ansible/single-server-drupal8.yml
* Moved individual drupal configuration to templates
* Changed approval requirement from default
> Move drupal configuration to files and remove approval requirement

- .gitmodules
- modules/ckanext-ytp_main/ckanext/ytp/controller.py
* Archiver updated to use interface for fetching resource_uploaded instead of default one.
* Cloudstorage updated to implement required get_path
* QA updated to use single logger instead of passing it in function calls
* YTP Group controller updated to fix user list renders.
> Update Archiver and Cloudstorage with required API implementations

- modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py
- Added new configuration option 'delete_missing'
- Cooperates with force_all
> AV-130: Added 'delete_missing' option to sixodp_harvester

- .circleci/config.yml
Added new circleci job for linting ansible single-server.yml playbook and related roles.
> cirleci ansible-lint support added

- modules/ckanext-ytp_main/ckanext/ytp/helpers.py
- modules/ckanext-ytp_main/ckanext/ytp/schemas/organization.json
- Add `org_hierarchy`-field to organization schema
- Upgrade `ckanext-hierarchy`
- Merge custom functionality
- Fix translations to work with new `ckanext-hierarchy`
> AV-179 scheming org hierarchy

- cloudformation/instances.yml
- Removed obsolete MinLength Parameters
- Changed default HostedZoneId values to match current values
- Added AllowedPatter check to HostedZoneId parameters and whitelisted ip addresses
- Added ALB with support for 1-4 SSL certificates and listeners for http and https
- Added target groups (http and https) for ALB
- Added DNS record for hosts public address
- Removed Elastic ip address
> AV-173: Added application load balancer and few smaller changes:

- ansible/inventories/infratest
- ansible/opendata_web_stack.yml
Playbook uses AWS Systems Manager Parameter store as a source for configuration
data. AWS profile name is required and was added to inventory file. As playbook
executed locally also ansible_python_interpreter variable needs to be configured
correctly.
> AV-180: Added ansible playbook for cloudformation stack creation.

- modules/avoindata-drupal-articles/avoindata_articles.routing.yml
- modules/avoindata-drupal-articles/js/avoindata-articles.js
- modules/avoindata-drupal-articles/src/Controller/ArticlesController.php
- modules/avoindata-drupal-articles/templates/avoindata_articles_block.html.twig
- modules/avoindata-drupal-events/avoindata_events.module
- modules/avoindata-drupal-events/avoindata_events.routing.yml
- modules/avoindata-drupal-events/js/avoindata-events.js
- modules/avoindata-drupal-events/src/Controller/EventsController.php
- modules/avoindata-drupal-events/templates/avoindata_events_block.html.twig
- modules/avoindata-drupal-theme/less/overrides.less
- modules/avoindata-drupal-theme/templates/node/node--avoindata-article.html.twig
- Added past events filter to events view.
- Modified the routing of events and articles modules so that the search
terms and other parameters are query parameters instead of parts of
route.
- Added change listeners to sort and filter elements so that the events
list search initiates when the values are changed.
- Changed wrong name of one class in less file.
> AV-193 Past events filter

- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/schemas/organization.json
- modules/ckanext-ytp_main/ckanext/ytp/schemas/presets.json
- Organization schema/preset fixes
- Default organization compatibility with new schema
- Disable ckanext-hierarchy's package controller to avoid conflicts
> AV-194 organization fixes

- ansible/roles/drupal/tasks/main.yml
- ansible/roles/drupal/templates/drupal_site_config/captcha.captcha_point.user_register_form.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/captcha.settings.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/recaptcha.settings.yml.j2
- drupal8/composer.json
- modules/avoindata-drupal-theme/less/overrides.less
- Added recaptcha extension to register page and modified ansible to add
default site configurations for the extensions.
- Edited registration page to follow the login page style.
Note:
This also includes AV-151 changes
> AV-150 User registration changes

- modules/avoindata-drupal-events/templates/avoindata_events_block.html.twig
- modules/avoindata-drupal-theme/config/install/contact.form.event.yml
- modules/avoindata-drupal-theme/config/install/core.entity_form_display.contact_message.event.default.yml
- modules/avoindata-drupal-theme/config/install/field.field.contact_message.event.field_event_submit_address.yml
- modules/avoindata-drupal-theme/config/install/field.field.contact_message.event.field_event_submit_end_time.yml
- modules/avoindata-drupal-theme/config/install/field.field.contact_message.event.field_event_submit_link.yml
- modules/avoindata-drupal-theme/config/install/field.field.contact_message.event.field_event_submit_picture.yml
- modules/avoindata-drupal-theme/config/install/field.field.contact_message.event.field_event_submit_start_time.yml
- modules/avoindata-drupal-theme/config/install/field.storage.contact_message.field_event_submit_address.yml
- modules/avoindata-drupal-theme/config/install/field.storage.contact_message.field_event_submit_end_time.yml
- modules/avoindata-drupal-theme/config/install/field.storage.contact_message.field_event_submit_link.yml
- modules/avoindata-drupal-theme/config/install/field.storage.contact_message.field_event_submit_picture.yml
- modules/avoindata-drupal-theme/config/install/field.storage.contact_message.field_event_submit_start_time.yml
- modules/avoindata-drupal-theme/less/overrides.less
- modules/avoindata-drupal-theme/templates/system/page--contact.html.twig
- Added contact form that can be used to "submit" an event to the
service. This sends email to form recipients.
> AV-89 Event submit

- modules/avoindata-drupal-theme/avoindata.theme
- modules/avoindata-drupal-theme/less/overrides.less
- Added reset password link to login form.
- Added register new account link to login form.
> AV-188 Login form links

- modules/ytp-assets-common/src/less/ckan/ckan.less
- Added some basic styling to report pages based on the new UX design.
> AV-21 Report page styling

- ansible/roles/datapusher/tasks/main.yml
Also installs datapusher requirements only if not present instead of latest
> AV-202: Install modified ckan service provider

- ansible/roles/ckan/templates/ckan.ini.j2
- modules/ckanext-ytp_request/ckanext/ytp_request/controller.py
- modules/ckanext-ytp_request/ckanext/ytp_request/logic/action/get.py
- modules/ckanext-ytp_request/ckanext/ytp_request/logic/auth/get.py
- modules/ckanext-ytp_request/ckanext/ytp_request/plugin.py
* Optimizes slow new membership queries
* Changes smtp port in ckan
> Optimize member requests and mail sending

- modules/ytp-assets-common/src/less/ckan/ckan.less
- Basic styling to ckan profile page based on UX design.
> AV-117 Profile page styling

- modules/avoindata-drupal-theme/less/overrides.less
- Breadcrumbs had some layout issues because admin panel was overwriting
display values for breadcrumbs.
> AV-159 Breadcrumb fix

- modules/avoindata-drupal-header/templates/avoindata_header_search_collapsible.html.twig
- modules/ytp-assets-common/src/less/mixins/mixins.less
- modules/ytp-assets-common/src/less/navbars.less
- Navbar search should now be displayed in almost similar style as the
one in UX demo.
> AV-169 Improved nav search styling

- modules/ytp-assets-common/src/less/ckan/ckan.less
- modules/ytp-assets-common/src/less/variables.less
- Functional hierarchy view with clickable plus and minus buttons
- Changed appearance of plus and minus buttons
- Moved the dataset count from left side to right side
> Organization listing page changes

- modules/avoindata-drupal-theme/config/install/core.entity_form_display.contact_message.event.default.yml
- modules/avoindata-drupal-theme/config/install/core.entity_view_display.contact_message.event.default.yml
- Fixing the email output of the event submit form (also fixes the
preview functionality). The proper config was missing and default values
did not include the new fields.
- Reordered preview location in form preview.
> AV-89 Fix event submit form display

- ansible/roles/ckan/vars/main.yml
- modules/ckanext-ytp_main/ckanext/ytp/templates/report/index.html
- modules/ytp-assets-common/src/less/ckan/ckan.less
- Additional improvements to report page responsiveness.
- All report page "boxes" should now be equal height of the row.
> AV-21 Additional improvements to report listing

- modules/ckanext-ytp_main/ckanext/ytp/templates/user/dashboard_organizations.html
- Choose user_dict from two sources, depends on whether pylons controllers or flask views are used
> AV-203: Fix user_dict reference to work with new style views

- ansible/roles/drupal/tasks/main.yml
- ansible/roles/drupal/templates/drupal_site_config/search_api.server.default_server.yml.j2
- ansible/roles/drupal/vars/main.yml
- drupal8/composer.json
- modules/avoindata-drupal-theme/config/install/block.block.guidemenuen.yml
- modules/avoindata-drupal-theme/config/install/block.block.guidemenusv.yml
- modules/avoindata-drupal-theme/config/install/search_api.index.guide_search.yml
- modules/avoindata-drupal-theme/config/install/views.view.guide_search.yml
- modules/avoindata-drupal-theme/less/overrides.less
- modules/avoindata-drupal-theme/templates/node/region--guide_menu.html.twig
- modules/avoindata-drupal-theme/templates/views/views-view.html.twig
- modules/ytp-assets-common/src/less/variables.less
- Guides are now seachable from the guide page. Implementation uses
search api extension.
- Modified guide related pages to pass the search terms to the correct
path.
- Modified guide menu configurations to have correct language settings.
> AV-133 Guide search

- ansible/roles/ckan/templates/ckan.ini.j2
- ansible/roles/ckan/vars/main.yml
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/ckanext-sixodp_showcase.pot
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/en_GB/LC_MESSAGES/ckanext-sixodp_showcase.po
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/fi/LC_MESSAGES/ckanext-sixodp_showcase.po
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/sv/LC_MESSAGES/ckanext-sixodp_showcase.po
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_greeting.html
- modules/ckanext-ytp_drupal/ckanext/ytp_drupal/i18n/fi/LC_MESSAGES/ckanext-ytp_drupal.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/license.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/sixodp_showcasesubmit/base_form_page.html
- modules/ckanext-ytp_main/ckanext/ytp/translations.py
> AV-176: Various language fixes

- ansible/roles/drupal/tasks/main.yml
Not having this configuration caused an error at provisioning
> Added configuration to main.yml list of deletable configurations

- ansible/roles/drupal/tasks/main.yml
- ansible/roles/drupal/templates/drupal_site_config/fontawesome.settings.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/update.settings.yml.j2
- modules/avoindata-drupal-theme/avoindata.libraries.yml
- modules/ytp-assets-common/src/resource.config
* Fixes resource order in ckan so that stylesheet are downloaded in correct order for overrides to work.
* Fixes font awesome paths in drupal configuration and theme
* Add cache clearing to ansible which has been on todo list for quite some time
> Fix vendor lib configs

- modules/avoindata-drupal-articles/avoindata_articles.install
- modules/avoindata-drupal-events/avoindata_events.install
- modules/avoindata-drupal-guide/avoindata_guide.install
Added comments for install hooks, because it might be confusing for future developers why the changes are not visible on the web page.
> Added comments explaining when install hooks are executed

- ansible/roles/drupal/templates/drupal_site_config/captcha.captcha_point.user_register_form.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/fontawesome.settings.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/update.settings.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/user.settings.yml.j2
- drupal8/composer.json
Updated drupal to 8.6.X, fixed captcha settings as they failed for missing formid, fixed missing account settings.
Things might break as drupal is updated, but these need checking case by case.
> Update drupal and fix account notifications

- modules/ckanext-ytp_main/ckanext/ytp/templates/user/read_base.html
is_myself is no longer in c parameter
> AV-236: Fix missing apikey

- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/controller.py
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/showcase/search.html
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/search.html
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_search_form.html
- modules/ytp-assets-common/src/less/ckan/ckan.less
- Added tag pills to showcase list view.
- Changed remove_field and drill_down_url in showcase controller to
target the showcase controller.
> AV-241 Showcase filters

- modules/avoindata-drupal-theme/config/install/views.view.guide_search.yml
- modules/avoindata-drupal-theme/less/overrides.less
- Added html tag trimming to guide result seach results.
- Modified result content font size
- Fixed issue with single guide page view with large images. Now they
should take max 100% width of parent div.
> AV-233 Guide search result styling

- modules/ckanext-ytp_main/ckanext/ytp/controller.py
- modules/ckanext-ytp_main/ckanext/ytp/templates/organization/admin_list.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/organization/user_list.html
> AV-183: Fix organization names in user lists

- ansible/roles/drupal/templates/drupal_site_config/user.settings.yml.j2
Also fixes drupal setting on admin approval required.
> AV-222: fix package count on organization search

- modules/ytp-assets-common/src/less/ckan/ckan_forms.less
-  Hide application search button text on small screens
> AV-260: Hide application search button text on small screens

- modules/ckanext-ytp_main/ckanext/ytp/templates/package/read.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/package_item.html
- modules/ytp-assets-common/src/less/ckan/ckan.less
- Added lock icons to private datesets in dataset lists and pages
> AV-113: Added lock icons to designate private datasets

- modules/ytp-assets-common/src/static_pages/404.en.html
- modules/ytp-assets-common/src/static_pages/404.fi.html
- modules/ytp-assets-common/src/static_pages/404.sv.html
- modules/ytp-assets-common/src/static_pages/css/main.css
- Preliminary work new style error pages, explicit line breaks
> AV-199: Styled error pages further

- modules/ckanext-ytp_main/ckanext/ytp/templates/user/edit.html
- make user edit template compatible with both pylons and flask contexts
> AV-279: Fix user edit page error

- modules/ytp-assets-common/src/less/ckan/ckan.less
Changed the minus button to use fontawesome pro icon and changed both of the buttons font size to 17px so that it matches the text height.
> Av 7 organization listing page styles

- modules/avoindata-drupal-hero/templates/avoindata_hero_form.html.twig
- modules/avoindata-drupal-theme/config/install/easy_breadcrumb.settings.yml
Fixed broken link on front page hero block.
> Av 296 broken organization list link

- modules/avoindata-drupal-theme/less/overrides.less
- Override the .btn-primary border-color with transparent
> AV-301: Fix infobox button border color

- modules/ckanext-ytp_main/ckanext/ytp/controller.py
- modules/ckanext-ytp_main/ckanext/ytp/templates/organization/members.html
- Correct permission check for organization member view
- FontAwesome fixes for the same view
> AV-285: check organization_update instead of group_update permission

- modules/ytp-assets-common/src/less/ckan/ckan.less
Category page seemed to be otherwise okay, but I switched the facet lists to using fontawesome icons. The CSS rules override the ckan default ones.
> Category page styles

- modules/avoindata-drupal-footer/templates/avoindata_footer_block.html.twig
I added Facebook link as the first (leftmost) icon since it was like this in current production environment as well.
> Added FB link to Finnish Open Data Ecosystem group

- modules/ytp-assets-common/src/less/ckan/ckan.less
- modules/ytp-assets-common/src/less/variables.less
- Make dataset description darker
- Added slight background color to file type tags
> AV-304: Changed dataset list colors

- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- Added `SESS<hash>` form cookie handling to ckan drupal snippets
> AV-311: Process both http and https cookies

- modules/avoindata-drupal-theme/less/overrides.less
- modules/ytp-assets-common/package-lock.json
- modules/ytp-assets-common/src/less/ckan/ckan.less
- modules/ytp-assets-common/src/less/navbars.less
- CKAN and Drupal footers should now be at the bottom of the page even
when there is little content on the page.
> AV-177 Bottom footer

- modules/ckanext-ytp_main/ckanext/ytp/commands.py
Fixes organization migration and adding users to groups.
> Fix migration scripts

- modules/ytp-assets-common/src/less/ckan/ckan.less
- Removed unnecessary paddings
- Changed button styles to prevent unwanted line breaks
> Improved organization listing page responsiveness

- modules/ytp-assets-common/src/static_pages/404.en.html
- modules/ytp-assets-common/src/static_pages/404.fi.html
- modules/ytp-assets-common/src/static_pages/404.sv.html
- Fixing the links in 404 pages to direct into correct page
(lang/contact).
> AV-200 Contact form links

- modules/ytp-assets-common/src/less/navbars.less
- Second navbar had issues with dropdown active colors. Now the active
links in second navbar dropdown menu should nolonger be highlighted with
blue background color.
> AV-413 Navbar colors

- modules/ckanext-ytp_main/ckanext/ytp/menu.py
- Hiding user delete item until delete user has been updated for drupal 8.
> AV-426 Hide user delete menu item

- modules/avoindata-drupal-header/templates/avoindata_header.html.twig
- modules/avoindata-drupal-theme/less/overrides.less
- modules/ytp-assets-common/src/less/navbars.less
- modules/ytp-assets-common/src/less/variables.less
- There were some differences between ckan and drupal header navbar
styling. Now the styling should be similar between the two "sites".
- The navbar alignment was bit off from the normal content. Now the
navbar content is as wide as the normal site content.
- Fixed some other small styling issues with navbar.
> AV-371 Header style unification

- modules/ckanext-ytp_main/ckanext/ytp/templates/user/dashboard.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/user/dashboard_datasets.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/user/dashboard_organizations.html
- modules/ytp-assets-common/src/less/ckan/ckan.less
- Fixed organization and dataset dashboard layouts that were pulling to
the right and had wrong widths.
- Other minor fixes to dashboard pages.
> AV-394 Dashboard layout fixes

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/templates/ckan.ini.j2
- Fix typo in smtp port number in defaults file
> AV-445: Fix if block line feeds in ckan config file

- ansible/roles/drupal/tasks/main.yml
- ansible/vars/common.yml
Creates test users in drupal.
Passwords need to be updated in secrets.
> AV-309: Create test users in drupal

- modules/avoindata-drupal-theme/templates/menu/horizontal-menu-base-template.html.twig
- modules/ytp-assets-common/src/less/navbars.less
- modules/ytp-assets-common/src/less/variables.less
- Fixed issues regarding nav bar stylings (mainly second navbar and
guide page navbar).
> AV-466 Nav styling fixes

- ansible/roles/nginx/tasks/main.yml
- ansible/roles/nginx/templates/nginx_redirect_sites.config.j2
- ansible/roles/nginx/templates/nginx_site_config.j2
- Remove yhteentoimivuus.fi redirect from snippet file
- Add new site config file containing redirects
> AV-443: Remove nginx listening localhost

- modules/ytp-assets-common/src/less/ckan/ckan.less
- The added padding on the ckan page template improves the mobile view
at least on dataset listing view and dataset view.
> Added padding for ckan mobile view

- ansible/inventories/prod
- ansible/opendata_web_stack.yml
- ansible/vars/environment-specific/prod.yml
- cloudformation/database.yml
- cloudformation/instances.yml
- Add environment spesific variables for prod environment
- Add support for prod named environment to database.yml
- Change dns record creation based on new parameter in instances.yml
- Add new parameter for dns record to opendata_web_stack.yml
> AV-420 Add new inventory file for prod environment

- modules/ckanext-ytp_main/ckanext/ytp/commands.py
- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
- modules/ckanext-ytp_main/ckanext/ytp/translations.py
Also includes migration script for converting them from current datasets.
> AV-366:  Change high value dataset category to International benchmarks

- ansible/roles/ckan/files/patches/enforce-url-decoding.patch
- ansible/roles/ckan/vars/main.yml
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- Added a patch that ensures URL decoding into unicode before handling (pending merge into core https://github.com/ckan/ckan/pull/4621)
- Changed drupal header fetching to take encoding into account
> AV-465: Ensure URL decoding with a core patch

- modules/avoindata-drupal-theme/avoindata.libraries.yml
- modules/ytp-assets-common/gulpfile.js
- Changing the upstream bootstrap location broke js references in the
theme. These changes should fix this issue.
> AV-482 Fix bootstrap library reference

- modules/ckanext-ytp_main/ckanext/ytp/logic.py
- I had not noticed to change drupal7 variable to drupal8. This has now
been fixed.
> AV-484 Fix typo in ytp_main

- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
- modules/ckanext-ytp_main/ckanext/ytp/translations.py
Internatiaonal benchmark had missing translations.
> Update translations on International benchmarks

- ansible/circleci_build_test.yml
- cloudformation/vpc_lockdown.json
Add descriptive tags to ec2 instances created by circleci
> Av 493 buid instance tagging

- cypress/integration/organization_spec.js
- modules/ckanext-ytp_main/ckanext/ytp/validators.py
When creating organization, context['group'] is None.
> Fix organization creation

- ansible/roles/ckan/files/patches/add_error_email_logger_to_flask.patch
- ansible/roles/ckan/vars/main.yml
The patch was merged to ckan core ckan/ckan#4623
> AV-474: Add error email logger core patch

- ansible/roles/ckan/vars/main.yml
This PR pulls from ckanext-dcat upstream to add structured_data plugin. Might fix catalog.rdf error too.
> AV-227: Update ckanext-dcat and add structured_data to plugins

- cloudformation/database.yml
- Add parameter for instance type
- Configure Enhanced monitoring
- Configure storing postgres logs to Cloudwatch
- Add parameter for enabling Performance Insights
- Add parameters for db engine version and AllowMajorVersionUpgrade
> AV-501: Add parameter for DBParameterGroup

- ansible/roles/ckan/files/patches/fix-popped-wrong-app-context.patch
- ansible/roles/ckan/vars/main.yml
- Fixes ckan/ckan#4431 "Popped wrong app context" errors
> AV-454: Fix popped wrong app context errors

- modules/ckanext-ytp_main/ckanext/ytp/templates/macros/ytp_layout.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_info.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_social.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/info.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/send_feedback.html
- modules/ytp-assets-common/src/less/ckan/ckan.less
- modules/ytp-assets-common/src/less/ckan/upstream_ckan/dataset.less
- modules/ytp-assets-common/src/less/ckan/upstream_ckan/mixins.less
- modules/ytp-assets-common/src/less/ckan/upstream_ckan/module.less
- Match dataset sidebar style to sidebar in organizations page.
- Cleaned some styles related to sidebar
> AV-242: dataset sidebar style

- modules/ytp-assets-common/src/less/ckan/upstream_ckan/nav.less
> AV-404: removed some styles that were causing issues

- modules/ytp-assets-common/src/less/ckan/ckan.less
- The sidebar module at the side now uses the same styles with other parts of the page
- Slightly bolder font for the sort order label
> Improve the organization edit page's dataset tab view

- modules/ckanext-ytp_main/ckanext/ytp/templates/package/search.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/additional_info.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_info.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/package/snippets/additional_info.html
- Removed content type from dataset sidebar if not interoperability tools
- Removed content type from additional info
- Removed content type facet if interoperability tools has not been selected
> AV-596: interoperability content type

- scripts/dataset_csv_export.py
- Updated ckanext-googleanalytics
- Added a new script for exporting csv data about interoperability tools retrieved through API
> AV-634: API for ckanext-googleanalytics, python script for csv export

- ansible/inventories/group_vars/all/apache.yml
- ansible/inventories/group_vars/all/nginx.yml
- ansible/inventories/group_vars/vagrant/apache.yml
- ansible/inventories/group_vars/vagrant/ckan.yml
- ansible/inventories/group_vars/vagrant/nginx.yml
- ansible/roles/drupal/molecule/default/playbook.yml
- ansible/roles/drupal/tasks/configure_drupal.yml
- ansible/roles/nginx/.yamllint
- ansible/roles/nginx/templates/server.config.j2
- cypress.json
Fix issues in local test environment by adding necessary configuration to nginx.
> AV-654 local test env settings

- modules/avoindata-drupal-articles/templates/avoindata_articles_block.html.twig
- modules/ytp-assets-common/src/less/drupal/overrides.less
- Date and tag list have more space between them
- Comma separation fixed in tag list
> Small article view layout improvements

- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- Changed facet title. Translation was pre-existing.
> AV-603: Changed tags facet title to popular tags

- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_info.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/tags.html
Unifies dataset info UI elements with keywords and fixes a bug where keyword links directed to showcases.
> AV-663: Fix content type indexing to solr

- modules/ckanext-ytp_main/ckanext/ytp/templates/package/resource_read.html
- modules/ytp-assets-common/src/less/ckan/resource_read.less
- modules/ytp-assets-common/src/less/ckan/upstream_ckan/module.less
- Added maturity label to resource view.
- Improved resource view styles and layout.
> Av 651 xblr taxonomy to resource

- ansible/inventories/group_vars/all/apache.yml
- ansible/inventories/group_vars/vagrant/apache.yml
- ansible/roles/php/defaults/main.yml
- ansible/roles/php/tasks/configure-fpm.yml
Remove obsolete if statements from apache configuration
> AV-621: Add process count configuration options to php

- .gitmodules
- ansible/roles/ckan/tasks/cron.yml
- check and send expiring dataset notification everyday at 10am
- sends a message about datasets expiring in 1, 5 and 14 days
> AV-676: updated submodule, added cron job to send expiring notifications

- modules/avoindata-drupal-footer/src/Controller/FooterController.php
- modules/avoindata-drupal-header/src/Controller/HeaderController.php
- Change cache-control header to public with max-age of 30 days
> AV-698: Allow caching of site header and footer

- ansible/roles/opendata_frontend/files/package.json
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_item.html
- modules/ytp-assets-common/package-lock.json
- modules/ytp-assets-common/package.json
- modules/ytp-assets-common/src/less/ckan/ckan.less
- modules/ytp-assets-common/src/less/drupal/bootstrap.less
Category list used the same layout as showcase list, this separates them.
Also updates some npm packages to fix security alerts.
> AV-721: Fix category layout

- Vagrantfile
- ansible/roles/solr/handlers/main.yml
- ansible/roles/solr/tasks/configure.yml
- ansible/roles/solr/templates/jetty9.service-solr.conf.j2
- ansible/roles/solr/templates/solr-jetty.xml.j2
- modules/avoindata-drupal-datasetlist/avoindata_datasetlist.module
- Change `Vagrantfile` base image
- Fix solr+jetty9 configuration and systemd unit
- Add missing parameters to `avoindata-drupal-datasetlist` since explicit parameters are required by the new PHP
> AV-667: Upgrade to Ubuntu 18.04

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/fix_unicode_decode_error_in_error_page.patch
The same patch as in https://github.com/vrk-kpa/api-catalog/commit/41ec635b81a91fa98a98a39f015922bc1c05a4bc
> Apply patch from ckan core PR, to fix flask error pages

- ansible/circleci_build_test.yml
Build test playbook randomly fails due to a race condition with cloud-init, fix by checking whether it is finished before moving on.
> AV-734 ansible role test fix

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/optimize_group_show.patch
- modules/ckanext-ytp_main/ckanext/ytp/controller.py
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/templates/organization/members.html
- scripts/generate_ckan_users.py
- Added a tool for generating test users to CKAN
- Added a patch for optimizing group/organization show and dictization in CKAN core
- Made linked_user compatible with user dicts
- Modified user list to take advantage of the above three changes
> AV-657 member list optimization

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/optimize_template_loading.patch
- Don't attempt to load non-existing template files twice, see ckan/ckan#4774
> AV-657: Added patch for optimizing template loading

- modules/ckanext-ytp_main/ckanext/ytp/templates/package/group_list.html
added `h.check_access('package_update', {'id': c.pkg_dict.id})`
> Show category addition only for users who have access to edit dataset

- modules/ckanext-ytp_main/ckanext/ytp/auth.py
Showcases are not related to organizations, so this check caused an error.
> AV-755 Organization check not applied for showcases

- modules/ckanext-ytp_main/ckanext/ytp/validators.py
Adding a showcase as an anonymous user caused an error, which this fixes
> Added null check for showcase validator

- modules/avoindata-drupal-theme/config/install/easy_breadcrumb.settings.yml
- Remove breadcrumb if home page is the only item
- The value in exported configuration had changed from 0 -> false, so I change it in our version control as well.
> AV-745 Remove breadcrumb from front page

- .circleci/config.yml
- ansible/circleci_cleanup.yml
- packer/packer-scheduled.json
- packer/packer-web.json
Separate creating and configuring an ec2 instance to job ansible-web and testing created instance with job cypress-web
> Av 803 cypress job to workflow

- .circleci/config.yml
Remove saving ami id to a file in packer-scheduled job as it is not used
> AV-803: Rename file storing web ami id in packer-web job

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/remove_gravatar.patch
- Core patch to disable showing gravatars
> AV-750: Remove gravatars

- ansible/roles/drupal/tasks/configure_drupal.yml
- ansible/roles/drupal/templates/drupal_site_config/locale.settings.yml.j2
User interface translations to english was not enabled, so modifications in transifex did not apply.
> Enable user interface translation to english in Drupal

- scripts/organization_csv_transport.py
- Export select fields from organizations
- Import only `producer_type` for now
> AV-808: Script for importing and exporting organization data

- scripts/dataset_csv_transport.py
Similar to AV-808, exports specific fields of all datasets into CSV and imports the same kind of CSV to update datasets. Currently only group memberships are updated.
> AV-809: Added a script for exporting and importing dataset data

- ansible/inventories/group_vars/beta/dynatrace.yml
- ansible/inventories/group_vars/prod/dynatrace.yml
- ansible/roles/dynatrace/README.md
- ansible/roles/dynatrace/defaults/main.yml
- ansible/roles/dynatrace/tasks/main.yml
- Add dynatrace groups for beta and prod environments
> AV-863: Add dynatrace role support for host groups

- ansible/inventories/group_vars/all/cloudwatch_agent.yml
- cloudformation/instances.yml
- Change log stream naming using environment name as a prefix
> AV-866: Change instance profile permissions to write log streams

- modules/avoindata-drupal-footer/config/install/block.block.footer_en.yml
- modules/avoindata-drupal-footer/config/install/block.block.footer_fi.yml
- modules/avoindata-drupal-footer/config/install/block.block.footer_sv.yml
- modules/avoindata-drupal-footer/config/install/system.menu.footer-en.yml
- modules/avoindata-drupal-footer/config/install/system.menu.footer-fi.yml
- modules/avoindata-drupal-footer/config/install/system.menu.footer-sv.yml
- Added blocks to `footer_content` region depending on language
- Each block holds a separate menu to create a multilingual menu system
> AV-815: Added per-language variants of footer menu for custom content

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/resource-reorder-translations.patch
- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/public/javascript/translations.js
Patch from core PR and added translations to ytp_main so that we can translate them in transifex.
> AV-739: Add translations to reorder resources

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/fix_unicode_decode_error_in_error_page.patch
This PR might fix the issue with organization feeds sending error email on not found organizations.
> AV-860: Update core patch with the one that was merged to core

- .circleci/config.yml
- Add deployment notifications to prod environment
- Add Release info to notifications
- Remove deployment notifications to service, application and host types
> AV-862: Add Dynatrace maintenance windows to deployments

- modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py
- Created tiny category mapping language
- Replace direct category mapping with new rules
> AV-885: predicate-based recategorization system for sixodp_harvester

- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/search.html
https://vrk-ejira.eden.csc.fi/browse/AV-880
I'm unsure if this was the only request that was in the ticket, should be checked.
- Added sorting by date created to dataset list
> AV-880: added sorting by date created to datasets list

- ansible/roles/ckan/files/patches/update_psycopg2_2.8.2.patch
- Amend psycopg2 core patch by also patchign requirements.txt, which is generated from the old requirements.in during install
> AV-902: also patch requirements.txt

- ansible/inventories/group_vars/beta/ckan.yml
- ansible/inventories/group_vars/infratest/ckan.yml
- ansible/inventories/group_vars/prod/ckan.yml
- ansible/inventories/group_vars/vagrant/ckan.yml
- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/tasks/configure.yml
- ansible/roles/ckan/tasks/main.yml
- ansible/roles/ckan/templates/sentry.patch.j2
Add Flask error reporting to Sentry
> AV-926 error tracking service

- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_info.html
- Default to an empty set of keywords if missing
> AV-951: Handle missing keywords robustly

- modules/avoindata-drupal-categories/templates/avoindata_categories_block.html.twig
- modules/ytp-assets-common/src/less/drupal/overrides.less
- Added a label to front page category items to show dataset count for each category
> AV-924: Added category dataset count tags to front page

- cloudformation/instances.yml
- Increase UnhealthyThresholdCount for solr lb
> AV-961: Increase timeout value for public lb

- ansible/roles/ckan/tasks/configure.yml
- ansible/roles/ckan/tasks/cron.yml
- ansible/roles/ckan/templates/beaker_session_cleanup.sh.j2
- ansible/roles/ckan/templates/ckan.ini.j2
Add scheduled cleanup script to remove sessions accessed over a week ago
> AV-899: Change beaker to use postgres db as backend

- modules/ytp-assets-common/src/less/drupal/overrides.less
- added layout styles for profile -> user settings page. (Only non admin)
Old styles were from edge to edge and no padding.
> AV-964: added basic layout styles for user edit form

- modules/avoindata-drupal-hero/templates/avoindata_hero_form.html.twig
- modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_result_text.html
- modules/ytp-assets-common/src/less/ckan/upstream_ckan/search.less
- modules/ytp-assets-common/src/less/helpers.less
- modules/ytp-assets-common/src/less/variables.less
- added links to advanced-search to frontpage and datasets page.
- removed rss feed button from datasets page
- updated dataset page element layout from floats => flex
- unified code tab style for the modified html files
> AV-849: added links to advanced search to frontpage and datasets page

- ansible/inventories/group_vars/beta/common.yml
- ansible/inventories/group_vars/infratest/common.yml
- ansible/inventories/group_vars/prod/common.yml
- ansible/roles/common/README.md
- ansible/roles/common/defaults/main.yml
- ansible/roles/common/tasks/main.yml
- Remove password requirement for using  sudo command to sudo group
> AV-973: Add support to common role for adding users

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/add_chaining_of_core_actions.patch
- modules/ckanext-ytp_main/ckanext/ytp/helpers.py
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/setup.py
Adds chained core actions from ckan master and adds all users to the group during creation as editors.
> Category improvements

- modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/package_item.html
- modules/ytp-assets-common/src/less/components/tag--producer.less
and added colors for education and research
> AV-939: moved producer types to bottom left

- modules/ckanext-ytp_main/ckanext/ytp/public/javascript/bulk-confirm-action.js
- modules/ckanext-ytp_main/ckanext/ytp/templates/organization/bulk_process.html
https://vrk-ejira.eden.csc.fi/browse/AV-978
> AV-978: added bulk action confirmation to dataset deletion

- ansible/roles/drupal/tasks/configure_drupal.yml
- modules/avoindata-drupal-theme/config/install/editor.editor.full_html.yml
- Added settings file for full_html editor
- Added style menu to full_html editor
- Added "responsive table" style to style menu
> AV-896: Added CKEditor settings with responsive table style

- modules/avoindata-drupal-appfeed/avoindata_appfeed.module
- modules/avoindata-drupal-appfeed/src/Plugin/Block/AppFeedBlock.php
- modules/avoindata-drupal-appfeed/templates/avoindata_appfeed_block.html.twig
Moved html generation of app list to function as lazy loaded components need the whole html to be lazy loaded.
> AV-1003: Add lazy loading to applist

- ansible/roles/ckan/tasks/cron.yml
- ansible/roles/ckan/tasks/database.yml
- ansible/roles/ckan/templates/ckan.ini.j2
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/info.html
Adds database initalization, cronjob and UI element for dataset update subscription.
> AV-984: Anonymous dataset subscription registration

- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/search.html
- If a user is logged in but cannot publish data, show a notification with instructions on the dataset page
> AV-746: Added a notification about publishing datasets

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/add_group_extra_resource_db_indices.patch
- Database indices for resource (package_id) and group_extra (group_id) to optimize view rendering
> AV-992: Patch to add migration for indices resource and group_extra

- .gitignore
- README.md
- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/implement_is_required_for_image_upload.patch
- ansible/roles/ckan/tasks/database.yml
- cypress/integration/advancedsearch_spec.js
- cypress/integration/category_spec.js
- cypress/integration/dataset_spec.js
- cypress/support/commands.js
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
- modules/ckanext-ytp_main/ckanext/ytp/schemas/presets.json
- modules/ckanext-ytp_main/ckanext/ytp/templates/macros/ytp_layout.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/upload_ex.html
- modules/ckanext-ytp_main/ckanext/ytp/validators.py
* Added support for is_required for image_upload
* Added a validator to use resource URL (now required) as the resource name if the name field is left empty
* Fixed initialization of the local test databases
> Av 997 add required attributes to resources

- modules/avoindata-drupal-datasetlist/avoindata_datasetlist.module
- modules/avoindata-drupal-datasetlist/templates/avoindata_datasetlist_block.html.twig
- modules/ytp-assets-common/src/less/common.less
- modules/ytp-assets-common/src/less/drupal/overrides.less
Only slight styling changes as the list is already made with flexbox
> AV-1028 & AV-1029: New styling for frontpage category list and dataset list

- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/schemas/organization.json
- modules/ckanext-ytp_main/ckanext/ytp/translations.py
- Added "country" producer type to organization schema
- Added "Country" to translations
- Updated translations
> AV-1047: Added Country producer type

- scripts/dataset_csv_transport.py
- scripts/organization_csv_transport.py
- Added `--ignore-errors` option for testing how many errors a CSV import would produce
> AV-909: Added ignore errors option to csv transport scripts

- modules/avoindata-drupal-appfeed/templates/avoindata_appfeed_block.html.twig
- modules/avoindata-drupal-datasetlist/templates/avoindata_datasetlist_block.html.twig
- modules/avoindata-drupal-theme/avoindata.libraries.yml
- modules/ytp-assets-common/src/less/drupal/overrides.less
Also fixes layout problem in Edge in hero header.
> Fix warnings of missing js files and missing icons on frontpage

- modules/avoindata-drupal-categories/avoindata_categories.module
- modules/avoindata-drupal-categories/src/Plugin/Block/CategoriesBlock.php
- modules/avoindata-drupal-categories/templates/avoindata_categories_block.html.twig
Moved HTML generation to php which replaces the categories content in twig.
> AV-1036: Use lazy loading for frontpage category list

- modules/avoindata-drupal-hero/src/Plugin/Form/HeroForm.php
- modules/avoindata-drupal-hero/templates/avoindata_hero_form.html.twig
- modules/ytp-assets-common/src/less/components/forms.less
Frontpage search implementation was incomplete and did not actually search at all.
> AV-1059: Fix frontpage search

- modules/ckanext-ytp_main/ckanext/ytp/commands.py
- modules/ckanext-ytp_main/ckanext/ytp/validators.py
Due to ckan issue single resource can't be updated without updating them all.
> Av 1060 migration fixes

- modules/avoindata-drupal-appfeed/avoindata_appfeed.module
- modules/avoindata-drupal-appfeed/templates/avoindata_appfeed_block.html.twig
- modules/avoindata-drupal-categories/templates/avoindata_categories_block.html.twig
- modules/avoindata-drupal-datasetlist/avoindata_datasetlist.module
- modules/avoindata-drupal-datasetlist/templates/avoindata_datasetlist_block.html.twig
- modules/avoindata-drupal-newsfeed/templates/avoindata_newsfeed_block.html.twig
- modules/ytp-assets-common/src/less/common.less
- modules/ytp-assets-common/src/less/drupal/overrides.less
Styles dataset list to use gradient fading out and adds common font-sizes which probably break things on the ckan side.
> AV-1068: Typography adjustments

- modules/ckanext-ytp_main/ckanext/ytp/helpers.py
- Added `country` to producer type helper
> AV-922: Add missing producer type to template helper

- ansible/roles/common/defaults/main.yml
- ansible/roles/common/handlers/main.yml
- ansible/roles/common/tasks/main.yml
Swapfile size is set to 1024Mb, can be adjusted from defaults.
> AV-1080: Enable swapfile and zswap

- ansible/roles/drupal/templates/drupal_site_config/metatag.metatag_defaults.front.yml.j2
- Only sow site name in frontpage title
> AV-853: Fix frontpage title

- modules/ckanext-ytp_main/ckanext/ytp/commands.py
- Added model, session and user to validation context
> AV-1083: More complete context for validators

- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/resources_list2.html
- Show different messages about datasets with no resources for maintainers and other users
> AV-977: Choose no resources message based on package_update privileges

- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/admin/manage_showcase_admins.html
- Showcase admin remove tried to use Sixodp_ShowcaseController which doesn't implement showcase admin remove
> AV-814: Use ShowcaseController for removing showcase admins

- modules/ytp-assets-common/src/less/components/forms.less
> AV-817: Fix file input rendering

- modules/avoindata-drupal-header/avoindata_header.module
- modules/avoindata-drupal-header/src/Plugin/Block/LoginBlock.php
- modules/avoindata-drupal-header/templates/avoindata_login.html.twig
* Lazy load drupal username in the header to avoid showing incorrect username due to a cached template
> AV-1063 Lazy load username

- modules/avoindata-drupal-theme/js/avoindata_custom_elements.js
* Fix toggling single expanders manually
* Fix properly opening or closing all expanders (instead of toggling all expanders)
* Reflect the expand/close all link text when toggling expanders manually
> AV-1103 Fix toggling of expanders

- .flake8
- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/side_effect_free-chained_action.patch
- Hide unapproved organizations the user is not a member of, unless the user is a sysadmin
- Patched both `organization_list` and `ckanext-hierarchy` to support this
> AV-931: unapproved organizations visibility

- modules/ckanext-advancedsearch/ckanext/advancedsearch/controller.py
- modules/ckanext-advancedsearch/ckanext/advancedsearch/fanstatic/javascript/avoindata-utils.js
- modules/ckanext-advancedsearch/ckanext/advancedsearch/fanstatic/javascript/clear-filter.js
- modules/ckanext-advancedsearch/ckanext/advancedsearch/fanstatic/javascript/ytp-datepicker.js
- modules/ckanext-advancedsearch/ckanext/advancedsearch/fanstatic/javascript/ytp-multiselect.js
- modules/ckanext-advancedsearch/ckanext/advancedsearch/i18n/ckanext-advancedsearch.pot
- modules/ckanext-advancedsearch/ckanext/advancedsearch/i18n/en_GB/LC_MESSAGES/ckanext-advancedsearch.po
- modules/ckanext-advancedsearch/ckanext/advancedsearch/i18n/fi/LC_MESSAGES/ckanext-advancedsearch.po
- modules/ckanext-advancedsearch/ckanext/advancedsearch/i18n/sv/LC_MESSAGES/ckanext-advancedsearch.po
- modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/datepicker-range.html
- modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/datepicker.html
- modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/multiselect.html
- modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/index.html
- modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/search_form.html
- modules/ckanext-advancedsearch/ckanext/advancedsearch/translations.py
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/package_item.html
- modules/ytp-assets-common/src/less/ckan/upstream-overrides.less
- modules/ytp-assets-common/src/less/components/advanced_search.less
- modules/ytp-assets-common/src/less/components/list--dataset.less
- modules/ytp-assets-common/src/less/drupal/overrides.less
**Waiting on confirmation from product owner**
**Waiting on confirmation from product owner on supported formats and then on the actual icons**
**Currently not feasible, would take a week+ of refactoring to either make a custom solution or to switch everything to use some existing component that supports this**
**Partially done, not all of the other fields exist yet either**
> AV-1093 tweaks to advanced search

- modules/ckanext-ytp_main/ckanext/ytp/dcat.py
- **dcat:Dataset**: dct:rights
- **dcat:Distribution**: dcat:temporalResolution, spdx:checksum
> AV-988: Added support for more DCAT-AP properties

- cloudformation/deployments.yml
- cloudformation/dev_deployments.yml
- packer/packer-scheduled.json
- packer/packer-web.json
> Revert "Av 1054 ami encryption"

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/add_drafts_to_search.patch
Backported the patch for ckan 2.8 and added it to ansible.
> AV-929: Add drafts to dataset search

- ansible/inventories/group_vars/prod/ckan.yml
- ansible/inventories/group_vars/vagrant/ckan.yml
- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/templates/ckan.ini.j2
- modules/avoindata-drupal-articles/src/js/main.js
- modules/avoindata-drupal-articles/webpack.config.js
- modules/avoindata-drupal-ckeditor-plugins/js/plugin.js
- modules/avoindata-drupal-events/js/avoindata-events.js
- modules/avoindata-drupal-header/src/js/main.js
- modules/avoindata-drupal-header/webpack.config.js
- modules/avoindata-drupal-hero/js/avoindata-hero.js
- modules/avoindata-drupal-theme/js/avoindata_custom_elements.js
Adds configuration option to control whether to send notifications or not. Default is false, but notifications are enabled in prod and vagrant (where they go to mailhog)
> AV-1183: Disable broken link notification on beta environment

- ansible/web-server.yml
- Added `dcatap` role to `web-server.yml` so it's applied to cloud installations
> AV-988: DCAT-AP extension

- modules/ytp-assets-common/src/less/drupal/custom-elements.less
- Implement line height with padding
- Set max width to title to avoid wrapping the icon
> AV-1173: Fix multiline guide expander titles

- ansible/roles/drupal/tasks/configure_drupal.yml
- ansible/roles/drupal/templates/drupal_site_config/captcha.captcha_point.contact_message_feedback_form.yml.j2
- ansible/roles/drupal/templates/drupal_site_config/captcha.captcha_point.user_register_form.yml.j2
Capthas got disabled due to syntax error.
> Fix syntax error in ansible and add missing labels to captcha elements

- ansible/roles/drupal/files/drupal8/composer.json
Install fails on newer versions.
> Lock Protected submissions to specific commit

- cypress/integration/showcase_spec.js
- modules/ckanext-ytp_main/ckanext/ytp/public/javascript/ytp_select2.js
Disabled trigger call as it marked form changed.
> AV-1209: Fix showcase form changed

- cloudformation/deployments.yml
Already deployed to aws and clamav deploy has succeeded in https://circleci.com/gh/vrk-kpa/opendata/16168
> AV-1208: Fix clamav deploy

- doc/dcat-ap/README.md
- Missing from previous commit
> Add DCAT-AP README.md

- ansible/roles/prh_tools/tasks/configure_prh_tools.yml
- ansible/roles/prh_tools/tasks/main.yml
When updating prod, only configure is applied.
> Move configuration of prh tools to configure file

- modules/avoindata-drupal-header/avoindata_header.links.menu.yml
> AV-1197: Added DCAT-AP menu item

- ansible/roles/ckan/tasks/cron.yml
> AV-1210: Rescheduled broken links notification to once a month

- ansible/roles/drupal/files/drupal8/composer.json
Adds easy_install to fix problems with beta deploy and update dependencies and syncs with drupal_project.
> Add easy_install and update dependencies

- modules/ckanext-advancedsearch/ckanext/advancedsearch/i18n/sv/LC_MESSAGES/ckanext-advancedsearch.po
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/sv/LC_MESSAGES/ckanext-sixodp_showcase.po
- modules/ckanext-ytp_comments/ckanext/ytp_comments/i18n/sv/LC_MESSAGES/ckanext-ytp_comments.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_request/ckanext/ytp_request/i18n/sv/LC_MESSAGES/ckanext-ytp_request.po
- scripts/combine_translation_csv.py
- scripts/update_translation_csv.py
- Update swedish translation files
- Update submodules with new translations
- Make translation CSV management scripts a bit more robust
> AV-1229: Update swedish translations, translation management scripts

- ansible/roles/opendata_frontend/tasks/pip.yml
- cypress.json
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/resource_read.html
- package-lock.json
- package.json
Updated Cypress.
Setuptools is updated to match ckan, googleanalytics requirements install was failing with old setuptools.
The errored test in cypress was due to broken google chart in resource read page.
> AV-1255: Fix Circle CI builds

- modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/organization/group_form.html
- vrk-kpa/ckanext-scheming contained a reference to ytp
- removed the reference, moved the old template to ytp_main to not change opendata
> Update ckanext-scheming, move old group form to ytp_main

- doc/dcat-ap/avoindata_dcat-ap_shacl.ttl
- Added shape restriction to dataset
> AV-1320: DCAT-AP validation

- doc/dcat-ap/avoindata_dcat-ap_shacl.ttl
- Merge DCAT-AP 2.0.1 changes to opendata extension
> AV-1344: Pull DCAT-AP 2.0.1 changes

- modules/ckanext-ytp_main/ckanext/ytp/dcat.py
Exception is not caught due to the call stack not as straight forward, I removed try except as it did nothing.
> Quote resource and external urls in DCAT AP profile

- modules/ckanext-ytp_main/ckanext/ytp/dcat.py
- modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py
- modules/ckanext-ytp_main/ckanext/ytp/helpers.py
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/validators.py
Limits fetched organization data in various places.
> AV-1342: Fetch only organization basic info

- .circleci/config.yml
- ansible/roles/drupal/files/drupal8/composer.json
- ansible/roles/drupal/files/drupal8/composer.lock
- ansible/roles/drupal/tasks/main.yml
Drupal updates have been done part of the build, this makes updating explicit. However requires manual work in the future, but builds are reproduciple.
> Add composer lock to version control

- ansible/inventories/group_vars/all/apache.yml
- ansible/inventories/group_vars/vagrant/apache.yml
- ansible/roles/ckan/defaults/main.yml
- ansible/roles/datapusher/molecule/default/playbook.yml
- modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py
Similar fixes as before, don't fetch unneeded data in places where only basic info is needed.
Also renames datapusher process from demo to datapusher and changed logging level for extension to debug as it is commonly used for useful information.
> AV-1342: Optimize memory use in harvester

- ansible/roles/common/handlers/main.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/php/tasks/configure-fpm.yml
- ansible/roles/redis/handlers/main.yml
- ansible/roles/redis/tasks/main.yml
- ansible/single-server.yml
Uses reporting cache for the location data, instead of generating it every time.
> AV-1339: Optimize statistics

- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/plugin.py
It should also fix an issue with platforms listed in application list
> Fixed a bug when trying to save application and it throws non-json error

- ansible/inventories/group_vars/beta/beta.yml
- ansible/inventories/group_vars/prod/prod.yml
Google analytics import creates new sites so these reflect those.
> Update matomo site ids

- modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/package/snippets/package_form.html
- modules/ckanext-ytp_main/ckanext/ytp/translations.py
- modules/ytp-assets-common/src/less/components/forms.less
Adds extras fields to dataset form, which can be modified is the maintainer wishes.
> AV-1398: Add extras to dataset form and update translations

- ansible/roles/ckan/templates/ckan.ini.j2
Drupal extension required modification to fetch user details.
> AV-1409: Limit public user details to signed in users

- modules/ckanext-ytp_main/ckanext/ytp/helpers.py
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/templates/activity_streams/activity_stream_email_notifications.text
- Added a new helper `site_url_with_root_path`
- Override activity notification email template to use the helper
> AV-1424: Fix activity notification email links

- ansible/roles/ckan/templates/ckan.ini.j2
- modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/scheming/package/read.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/base.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/read.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/resource_item.html
- modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/package_item.html
- Include apiset scheming schema
- Modify templates to fork apiset ones for further customization
- Fix breadcrumbs
> AV-1380: Apiset views

- cypress/integration/dataset_spec.js
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
- modules/ckanext-ytp_main/ckanext/ytp/schemas/presets.json
- modules/ckanext-ytp_main/ckanext/ytp/validators.py
Validates external_urls and resource urls, url_type needs to be added to schema as it gets populated later in core ckan and otherwise cannot be used in validator.
> AV-1431: Validate urls

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/templates/ckan.ini.j2
- cypress/integration/advancedsearch_spec.js
- cypress/integration/article_spec.js
- cypress/integration/category_spec.js
- cypress/integration/dataset_spec.js
- cypress/integration/general_spec.js
- cypress/integration/guide_spec.js
- cypress/integration/organization_spec.js
- cypress/integration/showcase_spec.js
- cypress/support/commands.js
- modules/ckanext-ytp_main/README.md
- modules/ckanext-ytp_main/ckanext/ytp/auth.py
- modules/ckanext-ytp_main/ckanext/ytp/plugin.py
- modules/ckanext-ytp_main/test.ini
- Remove support and settings for default organization
- Amend `package_create` auth function to check if user is a member of at least one organization
- Update README
- Fix several cypress tests
> AV-704: Remove default organization support

- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/fix_invalid_search_facets_template_error.patch
- modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form.html
- Add patch to fix `get_facet_items_dict`
- Fix `snippets/search_form.html` to function with missing search facets
> AV-1434: Fix search facet errors in organization view

- modules/ckanext-ytp_main/ckanext/ytp/resourcestatusplugin.py
There are errors on the mailing list, this should fix it.
> Fix key error as url_type might not exist

- amicopy/template.yaml
- ansible/opendata_web_stack.yml
- cloudformation/dev_deployments.yml
- packer/packer-scheduled.json
- packer/packer-web.json
add KMS CMK key for encrypting and sharing the AMIs to another account
> Av 1054 fix packer build encryption issue

- ansible/roles/ckan/templates/ckan.ini.j2
Related upstream issue in cloudstorage https://github.com/TkTech/ckanext-cloudstorage/issues/43
> AV-1456 and AV-1457: Re-enables datastore sql api and fixes hanging S3 upload

- modules/ckanext-ytp_main/ckanext/ytp/templates/report/deprecated_dataset_report.html
Changes made in ckanext-report submodule:
* Update jQuery tablesorter plugin
* Implement custom parser for dates
Changes in this module:
* Use the custom parser in the template for sorting dates
by adding it as a class where it is needed.
Refs AV-974
> AV-974: Update tablesorter and deprecated dataset report

- .circleci/config.yml
- .github/workflows/main.yml
- ansible/single-server.yml
Migrate code quality checks from CircleCI to GitHub Actions
> AV-1466: linting to GitHub actions

- modules/ytp-assets-common/src/less/navbars.less
- modules/ytp-assets-common/src/less/variables.less
- modules/ytp-assets-common/src/less/variables/palette.less
Fix vertical spacing issue with hover of navigation item when there's no active items currently
> AV-1510: Fix vertical spacing issue with main navigation item on hover

- modules/avoindata-drupal-appfeed/avoindata_appfeed.module
* Add null check for drupal appfeeds categories to prevent errors
> AV-1522: Fix fatal error from drupal app feed

- .circleci/config.yml
- ansible/ansible.cfg
- ansible/roles/ckan/defaults/main.yml
- ansible/roles/ckan/files/patches/set_error_email_logging_level_to_error.patch
- ansible/roles/secrets/tasks/main.yml
Adds a patch to ckan core to reduce error emails and fixes build problems.
> Reduce error emails by setting log level

- modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
- modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/radio_sysadmin.html
* Add new highvalue-field for dataset. 
* Add radio-input snippet that is visible for sysadmins only
> AV-1415: Add support to mark dataset as a high value dataset

- cloudformation/launchtemplate.yml
Installing the tools was failing and without functional tools the stacks were never updated and therefore deployment failed.
> AV-1561: Install python3 version of AWS tools

- packer/packer-scheduled.json
- packer/packer-web.json
EBS volumes are left as is which accumulate billing, they are really not needed.
> Delete packer volumes on termination

- modules/avoindata-drupal-guide/config/install/core.entity_form_display.node.avoindata_guide_page.default.yml
- modules/avoindata-drupal-guide/config/install/core.entity_view_display.node.avoindata_guide_page.default.yml
Removes disqus component from both guide page management and its display.
> AV-1584: Remove Disqus component from guide pages

- .github/dependabot.yml
- .github/workflows/check.yml
- .github/workflows/check.yml
- .github/dependabot.yml
> Restore accidentally removed linter and dependabot CI jobs

- .github/workflows/main.yml
- replace infratest job with beta job
- adjust condition so that it's run automatically for master branch
> AV-1569: Enable cdk beta deployment job

- cdk/bin/opendata.ts
Harvester processes are running out of memory.
> AV-1669: Increase memory for ckan cron containers

- scripts/generate_orgs.py
Fix a print statement to be Python3 compatible.
> fix(generate orgs script): Python2 -> Python3 fix

- cdk/bin/opendata.ts
- cdk/lib/backup-stack-props.ts
- cdk/lib/backup-stack.ts
- cdk/lib/database-stack.ts
- cdk/lib/efs-stack-props.ts
- cdk/lib/filesystem-stack.ts
- cdk/lib/rds-stack-props.ts
- cdk/test/ckan-stack.test.ts
- cdk/test/database-stack.test.ts
- cdk/test/drupal-stack.test.ts
- cdk/test/filesystem-stack.test.ts
Creates single backup vault per environment and adds efs and rds backup plans to it.
Adds default daily, weekly and monthly rules to backup plans.
> AV-1619: Add rds to backups and add daily,weekly,monthly rules

- cdk/bin/opendata.ts
Already deployed, this is only for version control.
> Enable backups in production

- cypress/e2e/user_spec.js
- cypress/support/commands.js
- cypress/support/index.d.ts
Cypress tests for testing the password policy module for drupal. Register a new user and attempt to change it's password.
> AV-935_cypress_tests

- cloudformation/kms_keys.yml
Template for adding environment specific kms keys to infrastructure, does not affect running environments.
> Add kms keys cloudformation template

- .github/dependabot.yml
Add various configuration for dependabot to update new dependancies.
> Add new configurations for dependabot

- .github/workflows/check.yml
- drupal/composer.lock
Upgrade drupal to 9.4.5 and dependencies to latest.
> Upgrade drupal and its dependencies

- cypress/e2e/dataset_spec.js
- cypress/support/commands.js
Contains tests for dataset sorting, some new tests related to datasets and a few changes to existing tests.
> fix(AV-1174): Dataset sorting tests

- cypress/e2e/user_spec.js
Fixed a this. -reference that was causing tests to occasionally fail
> AV-935: Fixed a test having a this reference which caused it to fail

- .github/workflows/master.yml
Tags built and pushed images as latest and with sha.
When build is not needed, adds sha to the latest image tags, so that each commit has 4 container referenced with sha. 
Deploy might still redeploy the image but that needs to be tested.
> AV-1787: Only build images that are changed

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/views.py
- docker/nginx/templates/server.conf.template
Remove nginx rule to hide feeds.
> AV-1740: Add functionality and route for recently added datasets feed.

- .github/workflows/master.yml
CDK deploys new container if the tag changes. This PR automatically modifies .env.template if needed.
> AV:1787: Commit new tags to .env.template and only deploy images that are built

- .github/workflows/changes.yml
- .github/workflows/master.yml
- .github/workflows/test.yml
- opendata-assets/README.md
There was a wrong name for previous step and the containers are not build before deploy.
> AV-1787: Fix detecting required container build on master

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
- Done to trigger rebuilding the CKAN container
> Remove extra import

- cdk/lib/ckan-stack.ts
- Remove mentions of non-existant private jena-fuseki repository
> AV-762: Download jena-fuseki from dockerhub

- ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/fanstatic/javascript/ytp-datepicker.js
After much deliberation, but not many decisions, this just adds the datepicker components own clear button under the calendar
> AV-1691: Add clear button to datepickers

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
Also add access_constraints as a fallback field for license url.
> AV-1757: By default, use non specified license for csw-harvested data.

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
Harvested datasets with resource-type "services" get now harvested as apisets
> AV-1778: geodcat api mapping for harvesting

- ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/helpers.py
Advanced search now displays only accepted organizations in the filter bar
> AV-1805: Advanced search displays only accepted organizations

- ckan/cron/crontab
- ckan/templates/production.ini.j2
Disables various notification emails as too many of them are reported as spam.
> AV-1826: Disable various notification emails

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/resource_form.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/resource_item.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/resource_item2.html
- cypress/e2e/apiset_spec.js
- cypress/support/commands.js
Fixed apiset resource read, edit and new routes to use /apiset instead of /dataset.
> AV-1839: apiset resource routing

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
Changed harvester apiset format mapping to format->formats
> AV-1822: Apiset resource format mapping when harvesting 

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
Also map categories with camelcase conventions as many of source categories seems to use that.
> AV-1846: Add category mapping for climatology, meteorology, atmosphere

- drupal/Dockerfile
- drupal/modules/avoindata-appfeed/README.md
- drupal/modules/avoindata-appfeed/avoindata_appfeed.info.yml
- drupal/modules/avoindata-appfeed/avoindata_appfeed.module
- drupal/modules/avoindata-appfeed/src/Plugin/Block/AppFeedBlock.php
- drupal/modules/avoindata-appfeed/templates/avoindata_appfeed_block.html.twig
- drupal/modules/avoindata-datasetlist/README.md
- drupal/modules/avoindata-datasetlist/avoindata_datasetlist.info.yml
- drupal/modules/avoindata-datasetlist/avoindata_datasetlist.module
- drupal/modules/avoindata-datasetlist/src/Plugin/Block/DatasetlistBlock.php
- drupal/modules/avoindata-datasetlist/templates/avoindata_datasetlist_block.html.twig
- drupal/scripts/init_drupal.sh
Restores deleted modules as drupal fails to start if the files are removed.
> Restore drupal modules to docker container

- ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/fanstatic/javascript/sixodp_showcase.js
- ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/base.html
- ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/read.html
- opendata-assets/src/less/components/showcase.less
Fixed issue on showcase-page that clicking image redirects user on new page instead of opening images in gallery-modal.
> AV-1863: Fix showcase gallery

- scripts/crawl_for_recursion_parent.py
Adds simple script that crawls every organization page to find organizations that are parents of themselves
> Add script for finding cyclical organizations

- drupal/composer.lock
Fixes issues with mail headers from and reply-to
> AV-1848: Update drupal/smtp to fix from or reply-to with mails

- drupal/modules/avoindata-articles/src/Controller/ArticlesController.php
- drupal/modules/avoindata-theme/templates/node/node--avoindata-article.html.twig
Fixes cache issue for articles category filtering
> AV-1868: Disable cache for article controller and fix query param in single article template

- docker/nginx/templates/server.conf.template
- drupal/modules/avoindata-theme/.gitignore
- opendata-assets/gulpfile.js
- opendata-assets/src/static_pages/404.en.html
- opendata-assets/src/static_pages/404.fi.html
- opendata-assets/src/static_pages/404.sv.html
- opendata-assets/src/static_pages/500.en.html
- opendata-assets/src/static_pages/500.fi.html
- opendata-assets/src/static_pages/500.sv.html
- opendata-assets/src/static_pages/css/main.css
- opendata-assets/src/static_pages/maintenance.en.html
- opendata-assets/src/static_pages/maintenance.fi.html
- opendata-assets/src/static_pages/maintenance.sv.html
Changes error pages from nginx defaults to opendatas own
> AV-1873: Fix error-page related paths. Add error pages css/static files into drupal theme in gulp build

- drupal/modules/avoindata-articles/src/Controller/ArticlesController.php
- drupal/modules/avoindata-newsfeed/src/Plugin/Block/NewsFeedBlock.php
Articles that are unpublished should now not appear in the front page feed nor on the articles page
> AV-1874: fix visible unpublished articles

- opendata-assets/src/less/drupal/overrides.less
- opendata-assets/src/less/navbars.less
Fixed button styling applying to unintended elements
> AV-1885: Fixed form button styling

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/group_list.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/read_base.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/search.html
Fixed the tabs appearing active for apiset changelog and groups tabs.
> AV-1859: apiset changelog active tab

- opendata-assets/src/less/drupal/menu.less
Removed numbering from the last 2 titles in an operating model
> AV-1881: operating model numbering

- drupal/modules/avoindata-theme/config/install/block.block.operatingmodelmenusv.yml
Changed the Swedish operating model label in drupal
> AV-1886: Changed Swedish operating model label

- ckan/Dockerfile
Test if this has any affect on crashing uwsgi.
> Remove unneeded version locks

- .github/workflows/test.yml
> AV-1958: add building datapusher container to test workflow

- .github/workflows/changes.yml
- .github/workflows/master.yml
- .github/workflows/test.yml
Upgrades deprecated dependencies.
Outputs changes from test.yml workflow so that detecting changes does not need run again.
Skips e2e and unit tests if nothing has changed.
> Only run e2e tests if containers or environment has changed

- .github/workflows/test.yml
Adds a job which will fail or pass based on the parallel test-e2e job statuses.
> Add result collect job

- .github/workflows/master.yml
- docker/datapusher-plus/Dockerfile
- opendata-assets/README.md
build-and-test-containers used in the checks were null as the job was missing in needs.
> Fix container tag writing to template

- .github/workflows/test.yml
- .gitmodules
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/hierarchy.py
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
- ckan/ckanext/ckanext-ytp_main/test.ini
- Use latest upstream ckanext-hierarchy
- Implement optimizations as an action override
- Override made with a chained action without calling the next action. This is a bit of a misuse, but avoids action declaration conflicts.
> AV-1772: Switch to upstream ckanext-hierarchy with overrides

- package-lock.json
- package.json
> Revert "Bump cypress from 11.2.0 to 12.7.0"

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/hierarchy.py
- Added `only_approved` parameter to `group_tree` action, so statistics can fetch only approved organizations even for admins
- Updated ckanext-statistics to use the parameter
> AV-1855: Support only_approved parameter to group_tree action

- docker/datapusher-plus/Dockerfile
Upgrade qsv to latest to fix utf-8 related problems.
> Upgrade qsv to 0.94.0

- .github/workflows/test.yml
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
- ckan/ckanext/ckanext-ytp_main/test.ini
- Added `after_organization_search` to filter unapproved organizations from sitesearch results
> AV-1975: Filter unapproved organizations in sitesearch

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/helpers.py
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/hierarchy.py
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/resources/opendata/scripts/opendata-hierarchy.js
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/resources/webassets.yml
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/organization/read_base.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/organization/snippets/organization_tree.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/organization/suborganizations.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/views_organization.py
- opendata-assets/src/less/components/organization-hierarchy.less
Adds new suborganization page to organizations:
Also styles it as suomi.fi styles which also affect profile pages:
> AV-1551: Add suborganizations page

- cloudformation/database.yml
Deployed to beta and prod, this just adds it to version control.
> [skip ci] AV-1982: Add autoscaling to rds storage

- drupal/composer.json
- drupal/composer.lock
- drupal/modules/avoindata-theme/templates/menu/vertical-menu-base-template.html.twig
- drupal/scripts/init_drupal.sh
- drupal/scripts/reinit_drupal.sh
Adds option to configure link attributes to menus. 
Also sets local dev environment to dev mode for easier debugging.
> Add menu link attributes to drupal

- drupal/composer.json
- drupal/composer.lock
Drupal dependencies need an update again.
> Update drupal dependencies

- cdk/bin/opendata.ts
- cdk/lib/certificate-stack-props.ts
- cdk/lib/certificate-stack.ts
- cdk/lib/elb-stack-props.ts
- cdk/lib/load-balancer-stack.ts
- cdk/lib/web-stack-props.ts
- cdk/lib/web-stack.ts
- cdk/test/load-balancer-stack.test.ts
Current certificates will need be deleted before new ones can be generated.
> AV-2012: Replace used SSL certificate with cdk generated one

- cdk/bin/opendata.ts
Increases memory of datapusher container in production to handle larger files.
> AV-2018: Increase memory in datapusher container

- ckan/ckanext/ckanext-ytp_request/ckanext/ytp_request/mail.py
- ckan/templates/production.ini.j2
- Added sending copies to ckanext-organizationapproval and ckanext-ytp_request
- Addresses configurable from ckan.ini
> AV-1894: Send admin notifications of org/member approvals

- cdk/lib/create-databases-and-users.function.ts
- cdk/lib/create-databases-and-users.ts
Code expects it to be datapusher_jobs
> AV-2010: Fix datapusher jobs database name and username

- .github/workflows/master.yml
- .github/workflows/test.yml
- opendata-assets/README.md
- Added `cache node_modules` step to master/test workflows
> AV-2066: Cache node_modules in CI workflows

- drupal/scripts/init_drupal.sh
Page is used as translatable static pages, it should not be deleted.
> Revert deleting content type page

- drupal/modules/avoindata-theme/config/install/block.block.faqmenufi.yml
- drupal/modules/avoindata-theme/config/install/system.menu.faq-menu-fi.yml
Add new menu and block by default.
> Add FAQ menu and block

- drupal/modules/avoindata-theme/js/cycle_guide_menu_items.js
- opendata-assets/src/less/drupal/menu.less
- Added ordinal numbers to bottom page switcher
- Added padding to active header item
- Added max-width to menu sidebar
> AV-689: guide menu style fixes

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
- Moved maintainer notes in dataset model to reorder dataset form fields
> AV-2044: move maintainer notes within dataset form

- drupal/modules/avoindata-theme/js/cycle_guide_menu_items.js
- drupal/modules/avoindata-theme/templates/node/node--avoindata_guide_page.html.twig
- opendata-assets/src/less/common.less
- opendata-assets/src/less/drupal/custom-elements.less
- opendata-assets/src/less/drupal/guide.less
- opendata-assets/src/less/drupal/menu.less
- opendata-assets/src/less/drupal/overrides.less
- opendata-assets/src/less/offcanvas.less
- Implement print style for guide pages
- Fix bug in cycle menu guide items in development environments
> AV-2101: Implement print style for guide pages

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/base.html
- Added language variant links to CKAN page header
> AV-2111: Added hreflang links to CKAN pages

- opendata-assets/src/less/drupal/custom-elements.less
- opendata-assets/src/less/variables/palette.less
- opendata-assets/src/less/variables/spacing.less
- Match table visual style to design system as closesly as viable
- Style could not be matched entirely to design system due to different use cases, like spanned cells
> AV-2112: make table style similar to design system

- drupal/modules/avoindata-theme/js/avoindata_custom_elements.js
- Make header `role=button`
- Add `aria-label` based on state
> AV-2089: Add a11y metadata to expander headers

- cdk/lib/ckan-stack.ts
Adds policies to allow exec and there for tunneling in solr container.
> AV-2198: Allow exec in solr container

- .github/workflows/open_prs.yml
Sends message to zulip if there are open ready pull requests made by other users than dependabot, run on schedule every weekday about 9 AM
> Add action for notifying on open PRs

- cdk/lib/ckan-stack.ts
Ckan cron container does not have access to upload in to s3 bucket, but prh tools need the permission, this grants the policy also for the cron container.
> AV-2006: Allow cron container to upload files to s3

- cdk/bin/opendata.ts
- cdk/lib/ckan-stack.ts
- cdk/lib/ecs-stack-props.ts
Reverts vrk-kpa/opendata#2020, increase is not longer needed.
> Revert "AV-2030: Increase prod datastore ephemeral storage"

- .github/workflows/restart_beta_containers.yml
- .github/workflows/restart_prod_containers.yml
Environments are in eu-west-1 instead of eu-north-1
> Use correct region in restart workflows

- cdk/lib/create-databases-and-users.ts
- cdk/lib/send-to-zulip.ts
Upgrades lambda nodejs runtime to v20 explicitly.
> AV-2225: Upgrade lambda runtimes to nodejs v20

- cdk/lib/ckan-stack.ts
- cdk/lib/drupal-stack.ts
> AV-2277: Decrease scaling trigger on ckan and drupal services

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
Missing translation in chips component was an affect of not having facet in filter list.
> AV-2232: search facets modification requires that facets are added

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/dcat.py
- doc/dcat-ap/README.md
- doc/dcat-ap/model.yml
- doc/dcat-ap/template.html.j2
- doc/dcat-ap/template.md.j2
- docker/nginx/www/ns/index.html
- Fix namespace page bootstrap CSS URL
- Fix Jinja errors from deprecated features
- Remove unused DCAT-AP terms
- Fix inconsistensies in profile and documentation
> AV-2237: DCAT-AP fixes

- ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/schemas/showcase.json
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/converters.py
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/group_list.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/group_checkbox.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/tests/test_plugin.py
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/views.py
- cypress/e2e/dataset_spec.js
Port of https://github.com/vrk-kpa/restricteddata/pull/268
> Refactor categories to groups

- drupal/composer.lock
> Upgrade drupal modules

- drupal/modules/avoindata-footer/templates/avoindata_footer_block.html.twig
Removes twitter logo and link from footer.
> AV-2378: Remove twitter link

- ckan/Dockerfile
- ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_search_input.html
- ckan/cron/crontab
- ckan/src/ckan/patches/remove_tracking.patch
- ckan/templates/production.ini.j2
- cypress/e2e/advancedsearch_spec.js
- cypress/e2e/dataset_spec.js
Does not include tests, as it is complex to test unused variable exists or is modified.
> AV-2384: Remove tracking due to performance reasons

- drupal/composer.lock
Updates drupal matomo module due to cve.
> Update drupal matomo module

- drupal/composer.lock
Some packages were missed in #2569
> Update drupal to 10.3.13

- cdk/lib/ci-test-stack.ts
Previous created two different policies, the new one has only one with all the access rights.
> Simplify test bucket policies

- cdk/package-lock.json
- cdk/package.json
- cdk/test/ckan-stack.test.ts
`aws-cdk-lib` and cli were incompatatible.
> Upgrade cdk cli to fix synth

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
- drupal/modules/avoindata-hero/avoindata_hero.module
Plugin names were wrong and integration error happened during merge, this will fix both of them.
> Fix frontpage statistics errors

- drupal/composer.lock
Updates drupal and all dependencies to latest patch version.
> Update drupal to 10.3.14

- drupal/composer.json
- drupal/composer.lock
Upgrades drupal to 10.4 and upgrades various dependencies to latest ones.
> AV-2428: Upgrade drupal to 10.4

- .github/workflows/prod.yml
Pre-existing tags failed, this checks existing tags using describe images and jq.
> Fix tagging existing images

- .github/workflows/prod.yml
Simplify tagging script for maintainability.
> Clean up tagging script for maintainability

- cdk/lib/lambda-stack.ts
- cdk/lib/send-to-zulip.function.ts
- clamav/clamav-docker/Dockerfile
- Select Zulip notification stream by message, default to "Service events"
- Fix container restart message parsing
- Upgrade clamav base image 1.3 -> 1.4
> AV-2187: Improve Zulip notifications

- cdk/lib/send-to-zulip.function.ts
- clamav/clamav-docker/src/app.py
- Add logging to clamav object tagging to debug why resource updates don't update infection information in the UI
- Simplify sendToZulip event handling code
- Try to fix event type deduction in sendToZulip
> AV-2187: Debug logging for clamav object tagging

- cdk/lib/shield-stack.ts
> Revert "AV-2440: shield protection can only have one healthcheck"

- cdk/bin/opendata.ts
- cdk/lib/shield-stack-props.ts
- cdk/lib/shield-stack.ts
> Revert "AV-2440: Add route53 health checks to shield protection"

- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/organization/index.html
- ckan/ckanext/ckanext-ytp_main/ckanext/ytp/views_organization.py
Changes default to show all organizations when user hasn't selected either. 
Adds hidden field to post the selection with the text search.
> AV-2446 & AV-2096: Show all organizations on default and fix a bug which lost the selection 
