vrk-kpa/opendata

ansible/roles/common_webserver/tasks/main.yml

- Gulp 4 uses gulp-cli global npm not gulp

Fix gulp for ansible

---

modules/ckanext-ytp_main/ckanext/ytp/templates/group/snippets/info.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/group/about.html

- Ckan groups about page was showing python dict of translations. Now it
should display only the value for current user language.

Fix ckan groups about page translation display

---

ansible/roles/drupal/tasks/main.yml

Fixed user roles creation task so that it ignores errors. Previously, this caused build process to fail if the roles existed already

User roles creation tasks ignores errors

---

ansible/roles/drupal/tasks/main.yml
ansible/roles/drupal/vars/main.yml

- Avoindata events module installation had been deleted. This now adds
the installation back to ansible files.

Fix avoindata events module install in ansible

---

modules/avoindata-drupal-articles/src/Controller/ArticlesController.php
modules/avoindata-drupal-events/src/Controller/EventsController.php
modules/avoindata-drupal-newsfeed/src/Plugin/Block/NewsFeedBlock.php
modules/avoindata-drupal-newsfeed/templates/avoindata_newsfeed_block.html.twig

- Custom modules should now properly load new node data when nodes are
created/update/deleted. This is done via cache node_list definition
within the modules. There might be room for improvementby creating own
custom cache tags which are invalidated when specific node types are
changed.
- Also fixed the front page "all events" link

AV 96 Custom module cache fix

---

ansible/roles/drupal/tasks/main.yml
modules/avoindata-drupal-header/avoindata_header.links.menu.yml
modules/avoindata-drupal-header/avoindata_header.routing.yml
modules/ckanext-ytp_main/ckanext/ytp/plugin.py

- Header menu has now logout and profile links that should only be visible for users that are logged in.
- CKANnow sends the drupal cookies with the footer and header api requests. This allows these menus to know whether the user is logged in even when user is browsing the ckan site.

AV 92 - Added logout to header menu

---

ansible/roles/drupal/vars/main.yml
modules/avoindata-drupal-header/templates/avoindata_header.html.twig
modules/avoindata-drupal-servicemessage/README.md
modules/avoindata-drupal-servicemessage/avoindata_servicemessage.info.yml
modules/avoindata-drupal-servicemessage/avoindata_servicemessage.module
modules/avoindata-drupal-servicemessage/src/Plugin/Block/ServicemessageBlock.php
modules/avoindata-drupal-servicemessage/templates/avoindata_servicemessage_block.html.twig
modules/avoindata-drupal-theme/avoindata.info.yml
modules/avoindata-drupal-theme/config/install/block.block.avoindata_servicemessage.yml
modules/avoindata-drupal-theme/config/install/core.entity_form_display.node.avoindata_servicemessage.default.yml
modules/avoindata-drupal-theme/config/install/field.field.node.avoindata_servicemessage.body.yml
modules/avoindata-drupal-theme/config/install/field.field.node.avoindata_servicemessage.severity.yml
modules/avoindata-drupal-theme/config/install/field.storage.node.field_severity.yml
modules/avoindata-drupal-theme/config/install/language.content_settings.node.avoindata_servicemessage.yml
modules/avoindata-drupal-theme/config/install/node.type.avoindata_servicemessage.yml
modules/ytp-assets-common/src/less/navbars.less

- Added node type servicemessage to Drupal
- Added avoindata-drupal-servicemessage plugin for storing, adding and rendering a service messages
- Modified avoindata-drupal-header to include service messages
- Added a service_messages region to avoindata-drupal-theme
Messages can be viewed in Drupal and CKAN. A message instance must be added for every language to be visible on pages of all languages.

AV-98 service messages

---

modules/ckanext-ytp_main/ckanext/ytp/templates/group/snippets/group_item.html
modules/ckanext-ytp_main/ckanext/ytp/templates/group/snippets/info.html
modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/info.html

- Category view didn't fetch the name and description translations to
the info bar. Now these should work when user changes the language.
- Also fixed view issue with package info bar that caused two "card
views" to be displayed on top of each other

AV 68 Category view translation

---

modules/avoindata-drupal-theme/config/install/core.base_field_override.node.avoindata_servicemessage.promote.yml

- Service message is no longer promoted to frontpage by default (message
is still displayed on the frontpage).

AV 137 disable servicemessage promote to front page

---

modules/avoindata-drupal-guide/avoindata_guide.install
modules/avoindata-drupal-guide/avoindata_guide.links.menu.yml
modules/avoindata-drupal-header/avoindata_header.links.menu.yml

Front pages of the open data guide are automatically created for Finnish, Swedish and English guide. The header has a link to this guide front page. The page doesn't have real content, but the content creator can add it later. 
All language versions of the guide page menu now have two top level submenus. These menus can be changed later, when actual content is created. 
Small translation changes

Guide front page automatically created for all languages and small guide menu changes

---

ansible/roles/drupal/tasks/main.yml
modules/avoindata-drupal-theme/config/install/field.field.node.page.field_basic_page_comments.yml
modules/avoindata-drupal-theme/config/install/field.storage.node.field_basic_page_comments.yml
modules/avoindata-drupal-theme/config/install/language.content_settings.node.page.yml
modules/avoindata-drupal-theme/config/install/node.type.page.yml
modules/avoindata-drupal-theme/templates/node/node--page.html.twig

-Made basic page content type translatable
-Added images and Disqus comments to the basic page
-Template changes for basic page
-Trying to delete configurations in Ansible doesn't result in an error anymore with a clean install

Translatable basic page and ansible configuration removal fix

---

modules/ckanext-ytp_request/ckanext/ytp_request/logic/action/create.py
modules/ckanext-ytp_request/ckanext/ytp_request/logic/action/get.py

- Member requests were failing becasue the sqlalchemy didnt save the
group relationship to member request correctly. Apparently the group id
was not enough for the relation ship.
- Also added some "none" checking to member_list_dictize to avoid
rendering errors incase email or group was missing from member request.

AV-162 Member request fix

---

modules/avoindata-drupal-appfeed/src/Plugin/Block/AppFeedBlock.php
modules/avoindata-drupal-categories/src/Plugin/Block/CategoriesBlock.php
modules/avoindata-drupal-datasetlist/src/Plugin/Block/DatasetlistBlock.php
modules/avoindata-drupal-hero/src/Plugin/Form/HeroForm.php

- Added basic error handling to Appfeed, Categories, Datasetlist and
Hero modules. Error handling response values to null or zero based the
data that module expects. Before this change the front page would hang
if ckan encountered exceptions during the request.

AV-184 Request error handling fixes

---

ansible/roles/ckan/vars/main.yml
modules/ckanext-ytp_main/ckanext/ytp/templates/sixodp_showcasesubmit/base_form_page.html

- Re-enabled the showcase submit module. Apparently it was disabled in
some merge or commit.
- Added proper breadcrumbs to the Showcase Submit view.

AV-40 Enable Showcase submit module

---

modules/ckanext-ytp_main/ckanext/ytp/commands.py
modules/ckanext-ytp_main/ckanext/ytp/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/schemas/presets.json
modules/ckanext-ytp_main/ckanext/ytp/validators.py

- Modify organization migration tool to perform translated->non_translated field patching
- Added new validator: `override_field_with_default_translation` that picks the default_locale translation from the current field and overrides another field's value with it
- Utilize `override_field_with_default_translation` in `fluent_core_title_translated` preset to apply it to relevant schemas

AV-194: Populate title from title_translated when available

---

modules/avoindata-drupal-events/src/Controller/EventsController.php
modules/avoindata-drupal-newsfeed/src/Plugin/Block/NewsFeedBlock.php

- Newsfeed now shows only events and articles from selected language
(fi/en/sv).
- Events in newsfeed are now filtered to show only future events.
- Fixed past filter in Events page to use "today" instead of "now" which
filtered events based on hours and minutes. We probably want filtering
only based on the date.

AV-171 Language aware newsfeed module

---

modules/avoindata-drupal-theme/less/overrides.less

`views-element-container` seems to be a container for stuff produced by the `views`-plugin. I didn't want to remove it entirely as based on my research it might break other things. Also I wanted to keep the RSS feed link in the page markup to maintain support.
- Hide RSS feed icon from front page
- Remove margin from `views-element-container` to make it visually disappear if there's no content

AV-158: Hide RSS subscription link on front page

---

modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/organization/about.html
modules/ckanext-ytp_main/ckanext/ytp/translations.py

- Override ckanext-hierarchy's template with default scheming one
- Extend `scheming_language_text` to work with multiple_checkbox fields
- Add missing translations

AV-185: Fix data rendering issues in organization/about

---

modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/date.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/fluent_markdown_ex.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/fluent_tags_with_autocomplete.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/fluent_text_ex.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/fluent_title.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/license.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/organization_ex.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/private.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/repeating.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/slug_ex.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/tag_list.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/text.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/text_ex.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/textarea.html
modules/ytp-assets-common/src/less/forms.less

- Made `field-assistive-text` class elements conditional and styled them a bit
- Removed URL field help text since it renders into the wrong place and would be complicated to fix

AV-160: improve form help text styles

---

ansible/roles/ckan/templates/ckan.ini.j2
modules/ckanext-ytp_drupal/ckanext/ytp_drupal/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/logic.py
modules/ckanext-ytp_main/ckanext/ytp/plugin.py

- Enabled certificate verification in ckan requests that use "requests" library. Local development verification is done by importing local cert.
This is branched of AV-207

AV-205 Request certificate verification changes

---

ansible/roles/ckan/templates/ckan.ini.j2

- CKAN config had wrong conditional check for AWS enviroments regarding
the drupal8 development cert.

AV-218 Fix CKAN development cert config

---

modules/ckanext-ytp_main/ckanext/ytp/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/templates/organization/read_base.html
modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/facet_list.html
modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form.html
modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form_without_input.html
modules/ytp-assets-common/src/less/ckan/ckan.less
modules/ytp-assets-common/src/less/ckan/upstream_ckan/nav.less
modules/ytp-assets-common/src/less/variables.less

-Changed name of action to fix an issue that the "Datasets" tab, didn't have the 'active' class, because actions using custom controllers could not have a same name with default pylons actions. 
-Changed icons to use fontawesome and changed their styles
-Changed active facet link color to black so it's the same as non-active link color. The activeness is still visible to the user by the cross icon

Av 8 organization page styles

---

modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/license.html

Added "license-title-text" class also for licenses that were defined. Previously, it was only used for undefined licenses.

Added style for defined license title

---

modules/avoindata-drupal-theme/config/install/core.entity_form_display.node.page.default.yml
modules/avoindata-drupal-theme/config/install/language.content_settings.node.page.yml

Previously, basic page was translatable and it had an image field, but these fields were not visible on the create/edit form. This was fixed by adding editing the configuration files.

Language and image fields made visible on basic page form

---

modules/avoindata-drupal-theme/config/install/core.entity_view_display.node.page.default.yml

Previously, the basic page content type had fields for image and comments and the image field was shown on the content creation page. However, the comments and image fields were not configured to be shown on the actual page itself. I fixed the issue by adding this new configuration file.

Added missing configuration file defining, which fields are shown

---

ansible/roles/drupal/templates/drupal_site_config/smtp.settings.yml.j2

Uses port 587 on aws instances and port 25 in local vagrant.

AV-108: Add smtp port to drupal configuration

---

ansible/roles/drupal/tasks/main.yml

Earlier, changes in URL alias patterns were not reloaded as part of deploying the new version. Now all modules are reloaded. However, reloading some modules unnecessarily caused some errors, which I ignore in the ansible script.

Reload all custom modules and ignore some errors

---

modules/ytp-assets-common/src/less/ckan/ckan.less

- Added padding or margin to header, breadcrumb and footer.
Before, their content was too close to the edge of the screen
on small screens

More responsive header, breadcrumb and footer

---

ansible/roles/drupal/tasks/main.yml

- Provisioning failed with clean installs, because the "Disable removed drupal extra modules"
task didn't work if Drupal was not installed. The task is now moved to later phase, when Drupal
is installed

Fixed ansible issue with clean installs

---

modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/search.html
modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/templates/group/snippets/group_item.html
modules/ytp-assets-common/src/less/ckan/ckan.less

- Replace left-margins with right-margins in media-grid items
- Remove extra padding where it misaligns leftmost content
- Fix fallout of the point above
- Unify category and application grid item layouts
- Translations

AV-18 category listing layout

---

modules/avoindata-drupal-theme/config/install/easy_breadcrumb.settings.yml

In some cases, there might be a need to have the breadcrumb title be different from the page title. However, Easy Breadcrumb offers a possibility to write lists of exceptions in the configuration. No such exceptions are configured now, but that can be done later if a need is noticed.

Use title in breadcrumb if possible

---

ansible/roles/drupal/vars/main.yml

- Added contextual to `removed_extensions` in ansible, also removes quickedit

AV-302: Remove 'contextual' module from drupal

---

modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json

The "email_validator" is one of the core validators so it doesn't need to imported specifically.

Added ckan email validators to email fields

---

modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/read.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/related_item.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/related_list.html
modules/ytp-assets-common/src/less/ckan/ckan.less
modules/ytp-assets-common/src/less/variables.less

- Showcase page had some issues with the pictures in the sidebar. These
were logos of other applications by the same user. These logos did not
fit well to our gray sidebar as the logos have no predefined size or
format specified (they can differ from the sites styling by quite a
lot). I decided to remove the imgaes from the sidebar altogether.
- The page had also some other issues with the applications logo in the
header that caused the title and other text to flow in very different
ways based on the logo size. Now the logo is on its own row and the
title and subheadings follow the logo after that.
- Other sidebar styling fixes.

AV-284 Single showcase page styling

---

modules/avoindata-drupal-appfeed/templates/avoindata_appfeed_block.html.twig
modules/avoindata-drupal-datasetlist/templates/avoindata_datasetlist_block.html.twig
modules/avoindata-drupal-hero/templates/avoindata_hero_form.html.twig
modules/avoindata-drupal-infobox/avoindata_infobox.module
modules/avoindata-drupal-infobox/src/Plugin/Block/InfoboxBlock.php
modules/avoindata-drupal-infobox/templates/avoindata_infobox_block.html.twig

- Some links in the front page components were missing the language
specific urls. Now all links pointing to CKAN should have the user
language as part of the url.

AV-268 Front page links

---

ansible/roles/common_webserver/files/package.json
modules/ckanext-ytp_main/ckanext/ytp/templates/organization/admin_list.html
modules/ckanext-ytp_main/ckanext/ytp/templates/organization/user_list.html
modules/ytp-assets-common/package.json

The userlist page failed, because the path to bootstrap-table was wrong, because the vendor folder was earlier removed. Now it was switched to using npm and the path was updated.

Switch bootstrap table to using npm

---

modules/ckanext-ytp_main/ckanext/ytp/templates/group/snippets/info.html
modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/organization.html

The links are not necessary, because there is already the additional information tab

Remove redundant additional information links

---

modules/ytp-assets-common/src/less/ckan/ckan.less

Previously bootstrap default colors caused the follow button and probably some other buttons as well to have weird colors with certain states like :hover and :active. The colors were some shades of green or yellow and stayed there for a short time. I don't think this kind of behaviour would be wanted anywhere on the application so I didn't limit the fix for only the follow button.

Changed button colors with different states

---

modules/ytp-assets-common/src/less/ckan/ckan.less

- Matches are highlighted when using the filtering in the organization tree
- Plus and minus buttons' css is changed manually instead of .show() to prevent wrong class
- Filtering also shows parents of matches
- Removed blue background when clicking and holding buttons

 Fixed organization tree filtering and buttons being on wrong row

---

ansible/roles/drupal/tasks/main.yml

Drupal 7 migration checks were skipped in most cases and migration items were using wrong names.

Fix drupal7 migration

---

ansible/roles/drupal/tasks/main.yml
ansible/roles/drupal/templates/services.yml.j2

- Drupal cookie should now expire straight after session has ended.
- Added default services.yml jinja template to the ansible task.

AV-380 Drupal cookie expire time

---

ansible/roles/nginx/tasks/main.yml
ansible/roles/nginx/templates/nginx_security_headers.conf.j2
ansible/roles/nginx/templates/server.config.j2

- Fixed typo in Referrer-Policy header
- Removed dulicate headers from nginx root path (duplicates due to
drupal already inserting them).
- Added all headers to /data path as otherwise content type frame
options headers would be missing from ckan side.

AV-381 http header fixes

---

ansible/roles/nginx/templates/server.config.j2

- It was possible to download web.config from the root and empty
settings php file. Served files didn't have any secrets in them but it
is cleaner to just deny the access altogether. 
This change might have side-effects as some drupal files are served under sites/default. I did
however test most of the pages but this changed needs some more eyes on it.

AV-379 Deny specific dirs to be downloaded

---

modules/avoindata-drupal-theme/less/overrides.less

- Changed the css rule for img elements in avoindata articles so that the same rule works also for basic page. I tested that it still works for avoindata articles as well.

Set max-width for images for basic pages

---

modules/avoindata-drupal-appfeed/templates/avoindata_appfeed_block.html.twig
modules/avoindata-drupal-categories/templates/avoindata_categories_block.html.twig
modules/avoindata-drupal-theme/less/overrides.less

- Categories listing had some issues with long texts. Made a quick fix
for this with defined height for category item box.
- Empty logos for showcases were not handled properly in app feed
tempalte. Now the listing will not attempt to load any images if logo is
not defined.

AV-398 Frontpage tweaks

---

modules/avoindata-drupal-theme/less/overrides.less
modules/ytp-assets-common/src/less/ckan/ckan.less

- Sticky footer was overlapping on content with IE11. Removal of height
value fixes this overlapping issue, but removes sticky footer
functionality on IE11. On other browsers sticky footer should work just
fine still.

AV-412 Fixing ie11 sticky footer issues

---

modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form.html

- Dataset search cleared filters when sorting was changed or when search
input was sent. This was due to missing query params within the form.
Now the query params are included in the form.

AV-400 Dataset search tag issue

---

modules/avoindata-drupal-hero/avoindata_hero.module
modules/avoindata-drupal-hero/src/Plugin/Block/HeroBlock.php
modules/avoindata-drupal-hero/src/Plugin/Form/HeroForm.php

Uses lazy builder for dynamic ckan parts of the hero. This way template can cached but the values will still update if new datasets are added.
Integration queries do not supply session cookie so the data itself is only public. 
Similar thing probably needs to be done to new datasets list component.

AV-322: Lazy Load dynamic content to hero

---

modules/avoindata-drupal-hero/templates/avoindata_hero_form.html.twig

- Read more link in the hero had no path set. Seems like the link should
point to guide page so this functionality has now been added.

AV-358 Fix read more link

---

ansible/roles/ckan/defaults/main.yml
ansible/roles/ckan/templates/ckan.ini.j2

- Add variables for ckan smtp port and tls setting
- Remove duplicate smtp server definition when aws environment is defined

AV-445: Add smtp parameters for pylons/weberror middleware

---

ansible/roles/drupal/vars/main.yml

Drupal internal page cache is over aggressive and will be replaced by cloudfront. Frontpage stats will be cached in internal cache but not in dynamic cache.

Disable internal page cache

---

modules/ckanext-ytp_main/ckanext/ytp/auth.py
modules/ckanext-ytp_main/ckanext/ytp/controller.py
modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/templates/organization/admin_list.html
modules/ckanext-ytp_main/ckanext/ytp/templates/organization/user_list.html

User lists are now limited to sysadmins with authentication.
Duplicate usernames are now merged in lists with organizations and roles appended to single user object.

AV-183: Merge usernames in userlists and add auth checks

---

ansible/roles/ssl/tasks/main.yml
ansible/roles/ssl/templates/openssl.cnf.j2

- Changed SSL cert generation for vagrant to include the `subjectAltName` extension
- Generating the new key requires removing existing key/cert from `/vagrant`

AV-456: Added subjectAltName to vagrant ssl cert to fix logging

---

modules/ckanext-ytp_main/ckanext/ytp/commands.py

A new migration script was added instead of using the older "migrate" script, because that was related to an older data model migration.

Added new migration script for adding missing author email values

---

modules/ckanext-ytp_main/ckanext/ytp/helpers.py
modules/ckanext-ytp_main/ckanext/ytp/templates/user/list.html

- Make translation system more robust by handling cases where the given object is not a dict, doesn't have the field nor an extras-field by returning the given default value
- Only render job title if a translation for it exists

AV-453: Fix job translation errors

---

modules/ytp-assets-common/src/less/navbars.less

- Footer link hovers had incorrect styling. Now the style should follow
more closely the guidelines.
Old style:
New style:

AV-324 Footer link hover fix

---

ansible/roles/ckan/tasks/main.yml
ansible/roles/ckan/templates/apache.wsgi.j2
ansible/roles/ckan/templates/ckan.ini.j2

Previous #345 PR modified logfile paths, resulting all ckan logs to append into single log file, apache logs, harvester logs and other commands. This PR fixes that.

Fix ckan log files

---

modules/ytp-assets-common/src/less/ckan/ckan.less

- Text were overflowing from the containers in showcase listing view.
Styling for the containers have been now fixed for Chrome, Firefox and
IE.
Old view:
Fixed views:

AV-450 Showcase text overflow fix

---

modules/avoindata-drupal-categories/templates/avoindata_categories_block.html.twig
modules/avoindata-drupal-theme/less/overrides.less

- Improved the way categories are listed on frontpage so that the
categories are center aligned if there are not enough categories on the
same "line".

AV-451 Frontpage category flexbox

---

ansible/roles/common_webserver/files/package.json
modules/ytp-assets-common/gulpfile.js
modules/ytp-assets-common/package-lock.json
modules/ytp-assets-common/package.json
modules/ytp-assets-common/src/static_pages/css/main.css

Updated dependencies which gave warning in npm audit.
glob-watcher is installed because for some strange reason, older version was installed by default.
gulp-base64 was switched to gulp-base64-inline, as gulp-base64 was unmaintained.

AV-365: Update NPM dependencies

---

modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py
modules/ckanext-ytp_main/ckanext/ytp/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/validators.py

In spatial harvester, commits are deferred as spatial itself defers them before hand.
Sixodp harvester removes timeseries timestamps if they aren't datetimes, since HRI requested the change.

AV-389: Fix spatial harvesting and modify sixodp harvester

---

modules/ckanext-ytp_main/ckanext/ytp/templates/group/member_new.html

In CKAN, it's possible to invite users to organization and groups by email. This in turn creates user accounts, but our account handling is in drupal so we probably don't want to support this. Inviting users is already prohibited in ckan configuration.

AV-461: Remove inviting users by email address

---

modules/ytp-assets-common/src/less/ckan/ckan.less
modules/ytp-assets-common/src/less/ckan/ckan_forms.less
modules/ytp-assets-common/src/less/ckan/upstream_ckan/forms.less

- Improved layout for buttons and texts especially in mobile view in different forms.
- The changes were made in CSS to avoid changes in CKAN core. The -34px margin-top rule is to set the "delete" button on the same line with the "save" button. 
- Tested with dataset and organization forms

Improved mobile view for CKAN forms.

---

doc/README.md
doc/code-structure.md
doc/custom-modules-drupal.md
doc/local-development.md
doc/local-installation.md

- Custom module documentation did not describe current custom modules.
This commit creates a short base for the drupal 8 custom module
documentation that can be improved in the future.
- Fixed some markdown styling issues in other documentation files.

AV-490 Update custom module documentation

---

ansible/circleci_build_test.yml

Automatic shutdown and termination for EC2 instances created by CirleCI after a delay defined in CircleCI environment variable AWS_EC2_INSTANCE_SHUTDOWN_DELAY.

AV-496 circle ci ec2 cleanup

---

modules/ytp-assets-common/src/less/drupal/overrides.less

- Made a margin fix previously introduced in AV-371 only apply to wide screen layouts, because it breaks mobile menus

AV-494: Fix drupal mobile menu margins

---

ansible/roles/ckan/tasks/main.yml
ansible/roles/ckan/templates/ckan.ini.j2
ansible/vars/common.yml
ansible/vars/environment-specific/beta.yml
ansible/vars/environment-specific/dev.yml
ansible/vars/environment-specific/vagrant.yml

- Added ansible variable `profiling_enabled: false` and per-environment overrides
- Install graphviz and linesman if set
- Include linesman config into production.ini if set

AV-542: Added CKAN profiling support for development environments

---

ansible/roles/cloudwatch_agent/templates/amazon-cloudwatch-agent.json.j2
ansible/vars/common.yml

Add option to conditionally include cloudwatch agent procstat plugin configuration if they have been defined, and add cpu usage metrics to configuration for ckan and php-fpm

Av 501 procstat monitoring

---

cypress/integration/front_page_spec.js
modules/avoindata-drupal-theme/avoindata.theme
modules/avoindata-drupal-theme/templates/node/region--guide_menu.html.twig

- Added 'language' variable available for Drupal Twig templates
- Fixed guide search form to use an absolute path

AV-306: Fix guide search form action URL

---

modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py

Created organization tree might have some issues that need manual fixing, for example if parent organization has not been created yet, the child organization goes to the root level.  
This also fixes mapping between sixodp organization and opendata organization and also error which happens on the first harvesting if force_all is false.

AV-342: Modify sixodp harvester to create organization tree

---

modules/ytp-assets-common/src/less/drupal/overrides.less

This should be the default behavious nowadays and it is somewhat unclear why it needed to be added specifically. This also only affects the Drupal pages, but the momentum scrolling already works on Ckan sites.

Added momentum scrolling for iOS devices

---

modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/showcase/manage_datasets.html

- Use `sixodp_showcase` base template that uses correct plugin for breadcrumb link target

AV-480: Fix showcase dataset edit page breadcrumb link

---

modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/plugin.py

- `vocab_*` searches in Solr schema require special handling before indexing. This was already done for categories, but this change generalizes it for both categories and keywords.
- Requires search-index rebuild after deploy

AV-401: Added vocab_keywords property to showcases for solr searching

---

modules/ckanext-ytp_main/ckanext/ytp/plugin.py

- Added translated keywords to facets in dataset and organizations pages
Requires search-index rebuild: `/usr/lib/ckan/default/bin/paster --plugin=ckan search-index rebuild -c /etc/ckan/default/production.ini` and maybe apache restart.
related to this pr: https://github.com/vrk-kpa/opendata/pull/415. Might overlap a bit.
PS: the logic might be in the wrong place, comment if so. First change to plugins functionality 😄

AV-263: keywords to facet filters

---

modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/search.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_greeting.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_search_form.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_search_input.html
modules/ckanext-ytp_main/ckanext/ytp/templates/organization/index.html
modules/ckanext-ytp_main/ckanext/ytp/templates/organization/snippets/organization_primary_actions.html
modules/ckanext-ytp_main/ckanext/ytp/templates/package/search.html
modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form.html
modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form_without_input.html
modules/ytp-assets-common/src/less/ckan/upstream_ckan/search.less

- Added title to each page
- moved primary action buttons to right of title
- synced action button styles between pages
- made search bar the same on all pages
- changed found amount text to h2
- synced sorting style between pages
- synced horizontal ruler style between pages
- added margin to active filters

AV-608: customized main search pages to have similar styles

---

modules/ckanext-ytp_main/ckanext/ytp/templates/user/edit_user_form.html

The email field was readonly, but it did not look like it, due to missing class.

AV-666: Fix styling of email field in user edit form

---

ansible/roles/ckan/defaults/main.yml
ansible/roles/ckan/tasks/configure.yml
ansible/roles/ckan/tasks/database.yml

AV-716: Add explicit start to Supervisor services
- Supervisor services were only started via a handler triggered on Supervisor configuration file changes, but as a part of the play the services were also stopped if running. If configuration would not change and playbook was re-executed the services would stay stopped.

Av 716 supervisor harvester fix

---

modules/ytp-assets-common/src/less/offcanvas.less

Position: absolute caused the info boxes to be positioned on top of the listings on mobile views. The changed css rule affects only screens with resolution of max 768px so the change doesn't affect the desktop view.

Fix for broken dataset and organization listings (AV-717)

---

ansible/roles/ckan/defaults/main.yml
ansible/roles/ckan/files/patches/remove_user_activity_from_group_activity_list.patch

SQL query was already changed in CKAN master, with the new query groups do not show user activity in group activity lists.

AV-722: Remove user activity from group activity list

---

modules/avoindata-drupal-hero/js/avoindata-hero.js

For some reason, with logged in users the 'interactive' state never happens.

JS executed when state is 'complete'

---

ansible/roles/solr/templates/schema.xml.j2
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/schemas/showcase.json
modules/ckanext-ytp_main/ckanext/ytp/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/validators.py
modules/ckanext-ytp_main/setup.py

- Add permission_labels for showcase-admin in a plugin. This plugin can later be used for
controlling permissions of other roles as well.
- Allow multiple permission labels in schema
- Allow showcase-admins to edit private showcase into public

AV-773 Add permissions for showcase-admin

---

ansible/roles/ckan/defaults/main.yml
ansible/roles/ckan/files/patches/group_include_extras.patch

- Added a core patch to allow getting parent organization options with enough data for translation
- Changed ckanext-hierarchy to use the feature if it's available

Optimize organization edit page

---

modules/ckanext-ytp_main/ckanext/ytp/templates/package/new_resource.html

The javascript in form.js adds the datepicker for elements with the data-datepicker attribute. Earlier, the javascript was only added to the edit form, for some reason.

AV-798 Add the datepicker javascript for new datasets

---

modules/ckanext-ytp_main/ckanext/ytp/templates/user/list.html

Previously, main_organization caused page to result in internal server error. We don't need that and other customisations anymore so we can use the core version. However, we don't want to use the search, so that is still removed.

AV-798 Removed most of custom /user page implementation

---

modules/ckanext-ytp_main/ckanext/ytp/templates/package/new_resource_not_draft.html

Originally, I had tested with adding a resource when creating a new dataset. However, adding a new resource to an existing dataset uses a different template. The form.js is now added to that template as well.

AV-735 datepicker in adding resources for datasets

---

modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json

- Changed 'deprecated' field labels in dataset schema

AV-824: Better i18n'd labels for 'deprecated' field

---

cloudformation/launchtemplate.yml

- Change ami id parameters type from string to more specific
- Remove obsolete s3 secret copy commands
- Change lifecycle heartbeat timeout
- Change creation policy to use asg desired size as count

AV-873: Change web asg to use lifecycle hooks

---

modules/avoindata-drupal-appfeed/templates/avoindata_appfeed_block.html.twig
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/plugin.py

Adds same logic for resolving absolute image urls as showcase_show uses to package_search, which is used on the frontpage for showcase lists.

AV-872: Add absolute image links to showcases in package_search api

---

modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/package_item.html

Ensures that if there is invalid (ie. old datamodel) producer type, the template will not try to render label for it.

AV-870: Fix producer label in case of invalid producer type

---

ansible/roles/ckan/defaults/main.yml
ansible/roles/ckan/files/patches/update_psycopg2_2.8.2.patch

- adapt core patch to update psycopg2 and fix an incompatibility between psycopg2 and sqlalchemy

AV-902: Added patch to update psycopg2 to 2.8.2

---

ansible/roles/ckan/tasks/main.yml

- Move ckan patch task before install of ckan requirements to support patched requirements.txt

AV-902: Fix support for patched core requirements.txt

---

ansible/roles/drupal/templates/drupal_site_config/user.role.publisher.yml.j2

- Publishers had permission to edit only Full HTML content fields. Also allow more restricted ones.

Update publisher permissions to cover editing basic/restricted HTML

---

modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_info.html

- `keywords` is a dict of languages, not a list of keywords

AV-951: fix typo

---

modules/ckanext-ytp_main/ckanext/ytp/schemas/group.json

- Overridden validator lists disabled group title overwriting with a translated one when updating groups. Use preset-provided validator lists instead.

AV-946: remove preset validator overrides from group schema

---

modules/ckanext-advancedsearch/ckanext/advancedsearch/controller.py
modules/ckanext-advancedsearch/ckanext/advancedsearch/fanstatic/javascript/post_pagination.js
modules/ckanext-advancedsearch/ckanext/advancedsearch/fanstatic/javascript/ytp-multiselect.js
modules/ckanext-advancedsearch/ckanext/advancedsearch/helpers.py
modules/ckanext-advancedsearch/ckanext/advancedsearch/loader.py
modules/ckanext-advancedsearch/ckanext/advancedsearch/plugin.py
modules/ckanext-advancedsearch/ckanext/advancedsearch/search_fields.json
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_field.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/datepicker-range.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/datepicker.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/multiselect.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/radio-select.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/search-and-target.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/search-bar.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/index.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/search_form.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/snippets/multiselect-choice.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/snippets/post_pagination.html
modules/ckanext-advancedsearch/ckanext/advancedsearch/tests/test_plugin.py
modules/ytp-assets-common/src/less/forms.less

- Query helper functions (field: `query_helper`) to generate solr query parameters for input fields. These are defined in the schema file. The solr query is built based on these.
- Return previous query to the UI so it can display the previous query.
- Made pagination work with POST request.
- It uses the previous query values and builds a new hidden form with the new page parameter also included and submits it.
- This is done with Javascript in the "post-pagination" file.
- Changed daterange input `start` and `end` fields to `before` and `after` to match the UI spec.
- Added `selected-` helper functions to populate custom fields with the prev query selected values.
- Added styles for pagination that uses buttons instead of links.
- Moved some imports to the top scope.

AV-953: advanced search functionality

---

modules/ckanext-ytp_main/ckanext/ytp/harvesterstatusplugin.py

- In some cases a harvester may report `None` in its `last_job_status` field. Handle these without crashing.

AV-805: Handle harvesters with None as last_job_status

---

modules/ckanext-ytp_main/ckanext/ytp/commands.py
modules/ckanext-ytp_main/ckanext/ytp/harvesterstatusplugin.py

- Better information from `harvester_status`
- Filtering options for `harvester_status`, default to skipping manual and never run harvesters
- Better error handling for `opendata-harvest send-status-emails`
- Command line options for `opendata-harvest send-status-emails`

AV-805: Better harvester reporting

---

ansible/roles/ckan/defaults/main.yml
ansible/roles/ckan/files/patches/json_serializable_lazyjsonobject.patch

- Added `for_json` method to LazyJSONObject with a patch, that makes it compatible with simplejson's `loads` function when also given `for_json=True`

AV-982: Fix LazyJSONObject not JSON serializable errors

---

modules/ckanext-ytp_main/ckanext/ytp/helpers.py
modules/ckanext-ytp_main/ckanext/ytp/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/templates/package/resource_read.html

- A temporary way to view resource SHA256 sums on the UI:
- New helper that calls the `resource_status` action to update its state and returns the latest SHA256
- Added SHA256 sum to resource template technical details section using the helper

AV-994: Added a temporary way to view resource SHA256 sums

---

ansible/roles/ckan/templates/ckan.ini.j2
modules/ckanext-ytp_main/ckanext/ytp/dcat.py
modules/ckanext-ytp_main/setup.py

- Added `dcat` module to `ckanext-ytp_main` with a `ckanext-dcat` compatible DCAT-AP profile
- Added publishing parts for the profile to `ckanext-ytp_main/setup.py`
- Configured `ckanext-dcat` to use the profile

AV-985: Added DCAT-AP 1.2.1 compatible dataset profile

---

modules/ckanext-advancedsearch/ckanext/advancedsearch/fanstatic/javascript/ytp-multiselect.js

- Add a global event handler per dropdown that closes it when something else gains focus

AV-1013: Close advanced search dropdowns when another element focuses

---

modules/ytp-assets-common/src/less/components/media-grid.less

- JQuery masonry couldn't fit three columns of 250px into the available space, make the items smaller to compensate
- If this isn't enough for all platforms, consider removing masonry and using flexbox

AV-1022: Change showcase grid item width to fit three columns

---

ansible/roles/drupal/files/i18n/en_GB/drupal8.po
ansible/roles/drupal/files/i18n/fi/drupal8.po
ansible/roles/drupal/files/i18n/sv/drupal8.po

Translation files now include all translations, as importing empty strings break some admin translations.
If translation does not exist it is the same as in the source string.

AV-877: Fix drupal translations

---

modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/additional_info.html
modules/ytp-assets-common/src/less/ckan/upstream-overrides.less

Using word-break: break-all due to IE not supporting smarter solutions.

AV-1061: Layout fixes for dataset additional info table

---

modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py

Assign datasets only to active organizations.
Generate name if it is already in use.

AV-886: Sixodp harvester fixes

---

cypress/integration/showcase_spec.js
cypress/support/commands.js
modules/ckanext-ytp_main/ckanext/ytp/templates/group/read_base.html
modules/ckanext-ytp_main/ckanext/ytp/templates/organization/read.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/organization_ex.html

- Add auth function to disallow creating datasets in non-approved organizations
- Hide non-approved organizations from organization list in dataset creation
- Hide create dataset button for non-approved organizations
- Fix tests to approve organizations where needed

AV-932: Disallow creating datasets in non-approved organizations

---

modules/ckanext-ytp_main/ckanext/ytp/commands.py

- Added a paster command `ytp-dataset validate` to `ckanext-ytp_main` that validates all datasets and reports any errors found

AV-1083: Added paster command to find invalid datasets

---

modules/ckanext-ytp_main/ckanext/ytp/plugin.py

- Override package_search action and set sorting to `metadata_created desc` if empty

AV-991: Override default dataset list order

---

.circleci/config.yml

Python 3.8 was released so our image was newer and pip 19.3 was released which does not work with aws sam.

Fix clamav lambda build

---

.gitmodules
ansible/roles/ckan/defaults/main.yml
ansible/roles/ckan/templates/ckan.ini.j2

- Added `ckanext-apis` to support API datasets
- Set `ckan.search.show_all_types` to `False` to exclude *apisets* from dataset search

AV-1091: Added support for apisets

---

ansible/roles/drupal/files/drupal8/composer.json
ansible/roles/drupal/tasks/configure_drupal.yml
ansible/roles/drupal/templates/drupal_site_config/registration_validation.settings.yml.j2

* Added drupal module [registration validation](https://www.drupal.org/project/registration_validation) to enable the possibility to blacklist email domains from registering accounts
* Configured to blacklist the specified domains by default and to give the suggested error message instead

AV-1024: Add drupal module to enable blacklisting domains

---

modules/ckanext-ytp_main/ckanext/ytp/dcat.py

- Implemented dct:dataset properties: dcat:landingPage, dct:spatial, dct:accuralPeriodicity, dct:type, dct:identifier, dct:temporal, dct:issued
- Implemented dct:distribution properties: adms:status, dct:license, dct:format, dcat:byteSize

AV-987: Implement some optional DCAT-AP fields for dataset/distribution

---

scripts/combine_translation_csv.py
scripts/update_translation_csv.py

- `combine_translation_csv.py` creates a new CSV based on three language specific CSVs created using the `po-csv` tool.
- `update-translation_csv.py` creates a new CSV based on a combined CSV, a language specific CSV and a language code
- Together these can be used to get a translatable CSV to translators, then to merge the result back into `.po` files

AV-1151: added quick scripts for combining/updating po-csv CSVs

---

cypress.json
cypress/integration/advancedsearch_spec.js
cypress/integration/article_spec.js
cypress/integration/category_spec.js
cypress/integration/dataset_spec.js
cypress/integration/front_page_spec.js
cypress/integration/general_spec.js
cypress/integration/guide_spec.js
cypress/integration/showcase_spec.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.d.ts
cypress/support/index.js
package-lock.json
package.json

* Adds retry functionality to cypress, it restarts current test if it fails, tries two more times.
* Adds logout_request command to cypress, which logs out the user without loading the full page.
* Refactors tests:
* general_spec was restructured and some tests removed as they were tested elsewhere.
* guide_spec was restructured.
* showcase_spec was refactored to load fewer pages.
Showcase edit page has an issue which causes electron to wait load event indefinitely and hangs rest of the tests.   https://github.com/vrk-kpa/opendata/compare/AV-1208_fix_builds?expand=1#diff-9844f442fbb52007e4c5771d7f3213eaR93-R95 these are therefore commented out for now.

AV-1208: Fix builds

---

ansible/roles/ckan/templates/ckan.ini.j2
ansible/roles/prh_tools/files/prh_clear.service
ansible/roles/prh_tools/files/prh_clear.timer
ansible/roles/prh_tools/tasks/configure_prh_tools.yml

The recipients are the same as in ckan_harvester_status_email_recipients, so that we don't need to create new secret variable.
Add clear command which is run on last day of month, and email notification when data is uploaded.

AV-1211: Update prh script

---

modules/ckanext-ytp_main/ckanext/ytp/templates/package/search.html

- Only show international benchmarks facet for sysadmins
- Fix Interoperability tools content type hiding to be language-agnostic

AV-1117: Hide international benchmarks search facet from non-admins

---

modules/ckanext-ytp_main/ckanext/ytp/commands.py

- Include all resources in patch
- If a string isn't over 0 in length, it should be 0

AV-1244: Fix temporal coverage migration script

---

modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_search_input.html

Showcase search had filtered pills and hidden params in the form. This PR removes the hidden ones.

AV-1254: Fix duplicate tags in showcase search

---

ansible/roles/dcatap/files/FOAF.ttl
ansible/roles/dcatap/files/avoindata_dcat-ap_shacl.ttl
ansible/roles/dcatap/files/index.html
ansible/roles/dcatap/tasks/main.yml
doc/dcat-ap/FOAF.ttl
doc/dcat-ap/README.md
doc/dcat-ap/avoindata_dcat-ap_shacl.ttl
doc/dcat-ap/template.html.j2
doc/dcat-ap/template.md.j2
modules/ckanext-ytp_main/ckanext/ytp/dcat.py

- Added FOAF and avoindata_dcat-ap SHACL schema files to doc
- Added documentation to dcat-ap namespace documentation templates
- Modified Ansible to include SHACL files in the documentation
- Modified DCAT-AP output to match the new validation

AV-1320: Added SHACL validation files for DCAT-AP output

---

.circleci/config.yml
cypress/integration/dataset_spec.js
cypress/integration/showcase_spec.js
cypress/support/index.d.ts
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/plugin.py
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/scheming/package/read.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/showcase/edit_base.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/edit_base.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/read.html
modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/snippets/showcase_item.html

Prevents rendering showcases as datasets and datasets as showcases.
Ansible-list install is modified as it doesn't install ansible by default anymore.
Rsa is pinned due to dropped support for py2.

AV-1342: Prevent rendering datasets with wrong types

---

modules/ckanext-ytp_main/ckanext/ytp/commands.py
modules/ckanext-ytp_main/ckanext/ytp/reports.py

to reduce memory footprint of batch commands.
Our batch running instance is running out of memory due to daily cron commands. This should help as python code wont fetch 1000 datasets at once, although this multiplis calls to package_search.

Use smaller page_size in package generation

---

modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py
modules/ckanext-ytp_main/ckanext/ytp/plugin.py

If organization is is deleted or pending state, weirdness happens in different parts of the service. If local organization is not assigned, the default organization of the harvest source is used.
Also removes old metadata mappings from spatial which no longer exist.

Add harvested datasets only to active organizations.

---

.circleci/config.yml
ansible/circleci_build_test.yml

Circle CI has id_rsa.pub now for some reason, which breaks using id_rsa, this renames the key which is used with ansible.

Fix build ssh key use

---

modules/ckanext-ytp_main/ckanext/ytp/plugin.py

resource_created, resource_modified and resource_published aren't used in anywhere and there might be multiple dates in dataset-reference-date which will fail then later if there are multiple new extra keys added.

AV-1365: Remove unneeded parsing in spatial

---

ansible/roles/ckan/templates/ckan.ini.j2

By default ckanext-dcat will use site_url if base_uri is not set. site_url does not contain root_path and generated URL are missing /data/

AV-1330: Set dcat_base_uri to url which contain root path

---

cypress/integration/advancedsearch_spec.js
cypress/integration/category_spec.js
cypress/integration/dataset_spec.js
cypress/integration/showcase_spec.js
cypress/support/commands.js
modules/ckanext-ytp_main/ckanext/ytp/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/display_snippets/repeating_email.html
modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/repeating_text.html
modules/ckanext-ytp_main/ckanext/ytp/validators.py

- Add template for showing multiple email addresses in dataset page
- Add a validator for validating multiple email addresses
- Fix repeating_text form_snippet requiring all fields to be filled if the field is required
- Modify dataset.json schema to use repeating_text for maintainer email address input

AV-1366: Dataset schema support for multiple emails

---

ansible/roles/ckan/templates/ckan.ini.j2
ansible/roles/nginx/defaults/main.yml
ansible/roles/nginx/templates/nginx_security_headers.conf.j2

* Replaces wikimedia maps with OpenStreetMaps.
* Constructs CSP header from variables for easier diffs.
* Add disqus domains to default-src as the implementation has changed.

AV-1351: Replace maps with OSM and fix CSP errors

---

ansible/inventories/group_vars/beta/ckan.yml
ansible/inventories/group_vars/prod/ckan.yml
ansible/roles/ckan/defaults/main.yml
ansible/roles/ckan/tasks/cron.yml
ansible/roles/ckan/templates/ckan.ini.j2
modules/ckanext-ytp_main/ckanext/ytp/commands.py
modules/ckanext-ytp_main/ckanext/ytp/harvesterstatusplugin.py

* Adds new configuration options: URL for instructions and fault recipients as not everything is sent to them.
* Adds new command to send notification only if some harvester has been running more than 24 hours.
* Modifies harvester status action as stopped harvester does not have finished timestamp but its status in finished.

AV-1337: Send notification on stuck harvesters

---

clamav/clamav-docker/Dockerfile

This might need adjustments to builds after it is deployed.

AV-1397: Downloading initial virus definitions is not allowed anymore

---

ansible/roles/drupal/defaults/main.yml

Migration was done years ago, this disables the tools so that we can remove them from composer after all environments have been updated.

Remove drupal migration tools from use

---

modules/ckanext-ytp_main/ckanext/ytp/plugin.py

- Count distinct child group/package ids instead of the total number of joined rows

AV-1274: Fix organization listing child organization/package counts

---

cloudformation/instances.yml

This adds [WAF](https://aws.amazon.com/waf/) to Cloudformation templates. Updating stacks is a separate process which is not related to Github.

AV-1423: Add WAF to cloudformation templates

---

ansible/roles/drupal/tasks/configure_drupal.yml

Based on https://www.drush.org/latest/deploycommand/, tasks are reordered. entity-updates does nothing since drupal 8.7 ref https://www.drush.org/latest/commands/updatedb/

Reorder tasks based on drush deploy command

---

ansible/roles/datapusher/tasks/main.yml

Datapusher is supporting only python3 now and it has its own virtual environment so that can be upgraded as well.

Upgrade datapusher to fix its installation

---

modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/categories.html

For some reason sometimes categories do not have translations and it causes an error as you can't get from None.

AV-1435: Fix internal server error on the new dataset page

---

modules/ckanext-ytp_main/ckanext/ytp/templates/ytp/menu.html
modules/ytp-assets-common/src/less/navbars.less
modules/ytp-assets-common/src/less/variables.less

Highlight the current page in the navigation menu in the user's profile page.
Done in this commit:
* Add new class to navbars.less
* Add new color variable to .less file for easier re-use
* Utilize the the less class if the current menu entry has the
selected attribute in the html template
Refs AV-1107

AV-1107: Show current page in user profile navigation

---

ansible/opendata_cloudfront.yml
cloudformation/instances.yml

add AWS managed rules in counting state to be able to evaluate if the rules could be used to better manage bot traffic

AV-1343: AWS WAF Bot Control

---

modules/ytp-assets-common/src/less/navbars.less
modules/ytp-assets-common/src/less/variables.less

Fix the styling in the main navigation menu so it follows the suomi.fi
design standards.
* Change hover for nav items to a 4px border
* Show active page with gray background and a border-bottom
* Modify how the nav menu changes when resizing window
* Make sure dropdowns only have a left border when hovering
Refs. AV-1449

AV-1449: Main navigation styling

---

modules/ckanext-advancedsearch/ckanext/advancedsearch/action.py

Add filter to get only resourceformats from resources that are linked with active package/dataset

AV-1454: Exclude deprecated options from advanced searchs format filters

---

scripts/remove_organization_members.py
scripts/tests/test_scripts.py

Implement script which allows a systems administrator to remove
users from an organization.
The users which are removed are either of member, admin or editor
capacity.
The script uses the -r flag for specifying the organization's
name or id from the command line. There is also a dry-run functionality
implemented which does not make any changes to the database but prints
the same information to stdout as it would when run normally.
Refs AV-1447

AV-1447: Remove users from organization

---

modules/ckanext-sixodp_showcase/ckanext/sixodp_showcase/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
modules/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
modules/ckanext-ytp_main/ckanext/ytp/plugin.py
modules/ckanext-ytp_main/ckanext/ytp/templates/snippets/facet_list.html
modules/ckanext-ytp_main/ckanext/ytp/translations.py

The facet filter's "show more" and "show less" texts are updated to add the facet filter's title to the string instead of just displaying "Show More" and "Show Less" as it did in the previous version.
Some of the titles were updated to plural since singular and plural for were mixed for the titles. Dynamic string building was added to the template in order to build these strings. The strings are built with each facet's name instead of the title in order to create a unique string which can be translated into all three languages used.
Done in this PR:
- Template code for building strings
- Updated facet filter titles in Python code
- Added translations for Swedish, English and Finnish
- Slight update of Swedish translations since they were missing in some places

Av-1509: Update facet filter texts and translations

---

modules/avoindata-drupal-hero/templates/avoindata_hero_form.html.twig
modules/ytp-assets-common/generate_test_categories.py
modules/ytp-assets-common/src/less/components/forms.less
modules/ytp-assets-common/src/less/components/layout.less
modules/ytp-assets-common/src/less/drupal/overrides.less
modules/ytp-assets-common/src/less/variables.less

This PR takes care of some layout fixes and updates to the frontpage of avoindata.fi.
What has been done:
- Create a script for generating categories which can be used for local front-end development.
- Display the categories in the categories section in two rows instead of three in full screen.
- Remove the logo and the avoindata.fi text from the header.
- Update the layout of the search bar. Move drop down to the right side and modify small layout details.
- Fix the broken log in button at the bottom of the frontpage.

AV 1529: Frontpage Accessibility Fixes

---

modules/avoindata-drupal-theme/avoindata.theme

The navigation element should have the "is_active" css class on the element
if a user navigates to a page and its subpages.
Accomplish this by getting the base path used for the view, build a
full path by getting the alias of the base path and the language code.
Check if the url in the nav element exists in the full path, this will
essentially include subpages if they are under the same baseurl and the
is_active class will be set on the corresponding "parent" element.
Implement a helper function for getting the language code from the
$hook variable.
Refs. AV-1474

AV-1474: Add active class on nav subpages

---

modules/ckanext-ytp_main/ckanext/ytp/harvesters/sixodp_harvester.py

Change license_id of harvested dataset to lowercase to prevent "unrecognized" license_id:s

AV-1562: Fix issue with incorrectly shown license tags on harvested resources

---

ansible/roles/drupal/files/site_config/block.block.breadcrumbs.yml

Add configuration file for omitting the breadcrumbs from the /guide pages.
Done in this PR:
- Generated .yml config and added it to the correct folder where it will be automatically installed.
Refs AV-1576

AV-1576: Remove breadcrumbs from guide page

---

ansible/inventories/group_vars/build_test/build_test.yml

Drupal article page generates an error for some reason if disqus is not initialized.

Add disqus site to build environment

---

.github/workflows/main.yml

`continue-on-error` marks the step as success even on failure, this should fix that.

Only upload cypress artifacts on failure

---

docker/README.md

The instructions were unclear on how to setup the docker project.
Add step-by-step instructions for new developers to set up the project
in order to simplify the process of getting started.
Refs None.

Update readme with setup instructions

---

cdk/lib/ckan-stack.ts

Similar to #1429, the previous fix did not affect ECS infrastructure.

Increase datapusher limits

---

cdk/bin/opendata.ts
cdk/lib/backup-stack-props.ts
cdk/lib/backup-stack.ts
cdk/lib/database-stack.ts
cdk/lib/filesystem-stack.ts
cdk/test/ckan-stack.test.ts
cdk/test/database-stack.test.ts
cdk/test/drupal-stack.test.ts
cdk/test/filesystem-stack.test.ts

Deploy fails due to invalid token, disable rds backups to vault for now.

Disable rds backup selection due to cdk bug

---

cypress/support/commands.js

Force create apiset-command to fill slug manually instead of assuming that autogeneration would be ready while typing title.

Fix apiset tests

---

cdk/bin/opendata.ts
cdk/lib/web-stack-props.ts
cdk/lib/web-stack.ts

Nginx container was using env var NGINX_ROBOTS_ALLOW [(opendata-nginx/nginx/jinja2-templates/robots.txt.j2)](https://github.com/vrk-kpa/opendata-nginx/blob/30f257142084c6d1afb9d0ad9f71c38b6ae65f72/nginx/jinja2-templates/robots.txt.j2#L3) to determine whether robots should be allowed (in prod) or not. The only issue being that env var was never set.

AV-1770: Add missing env var to allow robots for prod

---

ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/cli.py
ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/schemas/showcase.json
ckan/scripts/init_ckan.sh
cypress/e2e/showcase_spec.js
cypress/support/commands.js

- Add website as an platform-vocabulary-option.
- Remove showcase_type property.
- Add migration script to migrate website-values from old type-field to platform
Replaces [pull request](https://github.com/vrk-kpa/opendata-ckan/pull/113)

fix(AV-1752): Include website in showcases platform options

---

cypress/e2e/user_spec.js

Tests where randomly failing when drupal password policy validation hadn't finished before submitting the form.

AV-935: Fixed waiting for password policy validation

---

cypress/e2e/apiset_spec.js
cypress/support/commands.js

This PR updates the checkout version of ckanext-apis module, where a new "format" fields was added to the apiset schema. In addition, some updates to relevant cypress tests.

AV-1747: Add format field to apiset apis

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py

There was a flaw in how the update frequencies were calculated for apisets that had more than one dataset. Now the filters for update frequency are updated correctly

Av 1745 apiset filtering fix

---

.github/workflows/changes.yml
.github/workflows/master.yml
.github/workflows/test.yml
docker/docker-compose.build.yml
drupal/modules/avoindata-theme/README.md

Extend change detection to test workflows, now images are pulled from registry if there is no need to rebuild them, might make workflows slightly faster.

AV-1787: Only build required images during tests

---

.github/workflows/changes.yml

base is ignored on pull requests. This therefore should detect changes between successful deploy and current commit.

Fix building containers on master when there are multiple merges

---

cdk/lib/ckan-stack.ts

- Fuseki container should receive `ADMIN_PASSWORD` environment variable instead of `FUSEKI_ADMIN_PASS`

AV-762: Fix fuseki container admin password environment variable name

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
cypress/e2e/apiset_spec.js

Removed update frequency from apisets, will no longer appear as a filter term or in the form. Update frequency still exists for datasets.

AV-1793: Remove update frequency from apisets

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py

Organizations with only deleted datasets will no longer appear with the filter "_Näytä vain dataa julkaisseet tuottajat_"

AV-1794: fixed organizations with deleted datasets 

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/helpers.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/read.html
cypress.config.js
cypress/e2e/apiset_spec.js
cypress/support/commands.js

Datasets can now be associated with datasets. Most of the functionality is implemented in the ckanext-apis submodule from AV-1694 and this PR contains the implementation of the submodule for the Apiset page along with e2e tests. Also adjusted the default timeout for cypress tests from 4 seconds (default) to 30 seconds in order to reduce timeout based failures.
Create apiset-dataset associations on the manage_datasets page:
Associated datasets will appear on the apiset's page:

AV-1497: Apiset related datasets page implementation

---

.github/workflows/prod.yml

Releases do not push tag anymore so the prod deployment didn't trigger.

Fix production deployment trigger to published release

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/organization/index.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/views_organization.py

Organization page navigation through paginated results now works correctly with the selected filter (organizations with datasets or all organizations)

AV-1808: organization page nav fix

---

ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/ckanext-sixodp_showcase.pot
ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/en_GB/LC_MESSAGES/ckanext-sixodp_showcase.po
ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/fi/LC_MESSAGES/ckanext-sixodp_showcase.po
ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/sv/LC_MESSAGES/ckanext-sixodp_showcase.po
ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/templates/sixodp_showcase/read.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/read.html
cypress/e2e/apiset_spec.js

Associated datasets/apis are now hidden by default if none have been added to a showcase or an apiset. Apis can now be associated with showcases.

AV-1827: hide empty associated resources

---

ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/controller.py
ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/helpers.py
ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/i18n/ckanext-advancedsearch.pot
ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/i18n/en_GB/LC_MESSAGES/ckanext-advancedsearch.po
ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/i18n/fi/LC_MESSAGES/ckanext-advancedsearch.po
ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/i18n/sv/LC_MESSAGES/ckanext-advancedsearch.po
ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/display_snippets/multiselect.html
ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/index.html
ckan/ckanext/ckanext-advancedsearch/ckanext/advancedsearch/templates/advanced_search/search_form.html
cypress/e2e/advancedsearch_spec.js

Apisets have been added to the advanced search and it now defaults to showing datasets and apisets.

AV-1818: Apisets to advanced search

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/apiset/resource_read.html

Updated the apiset resource page to contain additional information and fixed miscellaneous templating on the page

AV-1833: Apiset resource page fixes

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_state_banner.html

Fixed draft and deleted datasets having a broken image link for the notification banner.

AV-1815: Fixed broken image link for draft and deleted datasets

---

ckan/Dockerfile

Might have caused some issues in docker environment and harvest already had it removed in upstream, so this removes it from our environment.

Remove pyopenssl

---

drupal/modules/avoindata-hero/templates/avoindata_hero_form.html.twig

Removed the show all from each link in the hero and moved the link to the title of the resource

AV-1843: Removed the show all links from hero

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/views_organization.py

Organization not found causes generic 404 page as it looks for a template that does not exist.

Fix organization not found page

---

ckan/templates/production.ini.j2
docker/docker-compose.yml

Update matomo extensions and modifies configuration to ignore health check calls from analytics.

AV-1857: Enable api analytics tracking

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/en_GB/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/public/base/javascript/modules/resource-reorder.js
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/resources/opendata/scripts/translations.js
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/activity.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/read_base.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_info.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/license_rdf.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/scheming/package/snippets/additional_info.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/snippets/activities/changed_package.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/snippets/activities/new_package.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/snippets/activity_stream.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/snippets/search_form.html

AV-1844:
Updated the following texts to use apiset related terminology:
- Apiset like button title
- Apiset license title and text
- Apiset changelog and changelog page tab + feed
- Apiset search default text
- Apiset edit resources resource ordering button text + info text
AV-1845:
- Changelog links now uses the correct /apiset url
- License linkin to apiset now uses the correct /apiset url

AV-1844 & AV-1845: apiset text updates and link urls

---

.gitmodules
ckan/Dockerfile
ckan/src/ckan/patches/add_entity_type_to_package_get_index.patch

Harvesting failed in an error due to a bug in sitesearch. Harvest page of single harvest fails when organization and harvest have the same name, due to how ckan works, filed a PR to ckan to fix it, patch is with this PR as well.

Fix site search issues

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/snippets/facet_list.html

Category names should now translate correctly in the sidebar for datasets, apis and showcases

AV-1875: Fixed category names not translating in the sidebar

---

opendata-assets/src/less/components/forms.less

Dropwdown will now cover ab-datepicker input field properly

AV-1891: Fixed multiselect dropdown not covering new datepicker

---

cdk/lib/ckan-stack.ts

In AWS the files are in S3, no need to rewrite the URLs as the file is not requested from the container.

AV-1942: Do not rewrite urls in datapusher in AWS

---

ckan/ckanext/ckanext-sixodp_showcase/ckanext/sixodp_showcase/i18n/fi/LC_MESSAGES/ckanext-sixodp_showcase.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/read.html

* Updated apiset link datasets header from 'Used datasets' to 'Datasets provided by the API'
* Updated translation key 'Datasets in this apiset' into 'Datasets provided by the API' for consistency as it was already translated into that
* Added some missing translations to sixodp_showcase manage_apisets

AV-1985: Update translations

---

ckan/templates/production.ini.j2

Datapusher formats have been set to nonexisting format to disable automatic uploads.

AV-1942: Submit to datapusher after cloudstorage has finished multipart uploads

---

cdk/bin/opendata.ts

Resources are running low when datastore apis actively used, adding CPU requires 4GB minimum as well.

Double the resources of ckan service

---

ckan/Dockerfile
ckan/src/ckan/ckan-uwsgi.ini

Monitoring uwsgi can be done by running `uwsgitop /tmp/stats.sock`

Enable stats collection and extra threads and processes to uwsgi

---

drupal/Dockerfile

PHP was old and there was warnings about it in the logs.

Update PHP to 8.1

---

.github/workflows/check.yml
drupal/Dockerfile
drupal/composer.json
drupal/composer.lock
drupal/scripts/init_drupal.sh
drupal/templates/site_config/raven.settings.yml.j2

Requires #1822 to be merged first.
Adds sentry plugin (the previous name was raven) to drupal and configures it.

Add sentry to drupal

---

cdk/lib/web-stack.ts
docker/.env.nginx.local

Unpins sentry python sdk, so it will updated to latest automatically.
Loads js sdk from cdn as npm no longer has built sdks and add sentry cdn to allowed csp scripts.

Upgrade sentry and add sentry cdn to allowed csp scripts

---

cdk/lib/drupal-stack.ts

Sentry dsn was missing from drupal stack.

Add sentry dsn to drupal stack

---

.github/workflows/master.yml
.github/workflows/prod.yml
.github/workflows/test.yml
cypress/e2e/apiset_spec.js
cypress/e2e/dataset_spec.js
docker/datapusher-plus/Dockerfile
docker/docker-compose.build.yml
opendata-assets/README.md

Sets up 5 different machines to run tests in parallel.
Removes adding files in tests that do not need to test adding files, as there are separate tests for that.
Adds retrying to dataset an apiset tests as adding files is somewhat flaky.

Test parallelization

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/organization/snippets/organization_tree.html

- ckanext-hierarchy's default template fetches each organization separately to generate a title already present in our hierarcy tree objects. Remove the extra work to speed up page loads

AV-1772: Faster organization tree template

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/helpers.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/schemas/organization.json
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/org_hierarchy.html

- Add `keep_old_value_if_missing` to parent organization field to support control disabling
- Disable parent organization select if user is not an admin in currently selected parent organization

AV-1879 disable parent org edit if not parent admin

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/helpers.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/org_hierarchy.html

- Added option to `get_groups_where_user_is_admin` to only return approved organizations
- Used the option in parent organization selection control

AV-1880: Hide unapproved organizations in parent organization selection

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/hierarchy.py

- The id map will not contain filtered results, so we should skip them

Fix filtering to approved organizations breaking counting suborganizations

---

drupal/modules/avoindata-ckeditor-plugins/js/plugin.js

- Set `target=_blank` attribute in external links

AV-1961: Make external links in drupal content open in a new tab

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/helpers.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/scheming/form_snippets/org_hierarchy.html

- Handle `only_approved` in `get_groups_where_user_is_admin` also when `current_id` is defined
- Handle case where user is not an admin of the current parent organization, but is an admin of some other organization in addition to the one being edited.

AV-1880: Fix list of selectable parent organizations

---

cdk/bin/opendata.ts

Apparently analyzing larger csv files require more then 1GB memory.

AV-1981: Double datapusher task memory

---

drupal/modules/avoindata-header/src/Plugin/Form/SearchForm.php
drupal/modules/avoindata-hero/src/Plugin/Form/HeroForm.php

BuildForms should not have language attributes which generate errors in logs and sentry.

Forms should not have language attributes

---

docker/nginx/templates/security_headers.conf.template

PDF view is blocked by CSP object-src none header, this allow self for it and splits csp header for easier diffs in the future.

Fix security headers for pdfview

---

cdk/lib/web-stack.ts

Pdfview fails as it contains the file itself in iframe.

Allow including uploaded datasets to be included within iframes

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py

The syntax was all wrong for this, now maintainer will be empty if neither are available and it will be reported in harvester errors.

Parse maintainer from individual name if organization is missing

---

cdk/lib/ckan-stack.ts
ckan/Dockerfile

- use `crond` instead of `cron`
- the correct format is `ps aux` not `ps -aux`
- Added `nfs-utils` to installed packages

AV-2002: Fix ckan_cron healthcheck in CDK

---

ckan/scripts/entrypoint_ckan.sh

Reverts vrk-kpa/opendata#1936, cats will fail if files do not exist.

Revert "Output contents of lock files for debugging"

---

cdk/bin/opendata.ts

Loadbalancer requires certificate in the same region and cloudfront requires it to be us-east-1, so this creates both, cloudfront is in cloudformation stack so it does not automatically update with cdk.

AV-2012: use separate certificate for cloudfront

---

cdk/bin/opendata.ts
cdk/lib/bypass-cdn-stack-props.ts
cdk/lib/bypass-cdn-stack.ts
cdk/lib/drupal-stack.ts
drupal/templates/settings.php.j2

Adds api subdomain to route53, forwards the traffic to loadbalancer and allows the domain to be used in drupal.

AV-1993: Add bypass cdn stack and allow the host in drupal

---

cdk/lib/bypass-cdn-stack.ts
cdk/lib/certificate-stack.ts
cdk/lib/drupal-stack.ts

Changes domain for bypassing cloudfront from route53, certificates and trusted hosts in drupal.

Change bypass domain from api to vip

---

.github/workflows/test.yml
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
ckan/ckanext/ckanext-ytp_main/test.ini
ckan/scripts/init_ckan.sh
ckan/templates/production.ini.j2
docker/docker-compose.yml
docker/postgres/Dockerfile

Updates submodule to the already updated fork and with https://github.com/ckan/ckanext-spatial/pull/311 and https://github.com/ckan/ckanext-spatial/issues/301#issuecomment-1644978489
Postgis is no longer required so uses postgres container locally, postgis needs to be removed separately from rds instances. 
Also fixes docker compose to use built datapusher image from registry, instead of building it every time.

AV-1964: Update spatial

---

drupal/composer.json
drupal/composer.lock

This removes disqus from the composer and as such should remove any remaining disqus related files from the project. Make sure to merge this after https://github.com/vrk-kpa/opendata/pull/1976 is already in all environments

AV-2020: Remove disqus from composer

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/ckanext-ytp_main.pot
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/fi/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/i18n/sv/LC_MESSAGES/ckanext-ytp_main.po
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/schemas/dataset.json
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_state_banner.html
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/translations.py
opendata-assets/src/less/components/dataset.less

Add a multilingual textfield to dataset schema. 
If field has a value in selected language show a banner with the given note at the top of the dataset page

AV-1944: Add maintainer_note_translated to dataset schema

---

cdk/bin/opendata.ts
cdk/lib/ckan-stack.ts
cdk/lib/ecs-stack-props.ts

Datapusher-plus doesn't currently delete temp files so as a temporary fix this increases the ephemeral storage for datastore task to 100GiB

AV-2030: Increase prod datastore ephemeral storage

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/views.py

The main search is performed with edismax query parsing, so the partial result count queries should be as well

AV-2033: Perform site search partial result counts with edismax

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/spatial/snippets/spatial_query.html

- Leaflet was being loaded twice from two different webassets: once with Draw and once without
- Made Leaflet its own webasset in ckanext-spatial to prevent repeated loading
- Removed unnecessary assets from spatial query template

AV-2029: Fix dataset map search

---

ckan/templates/production.ini.j2

Updates matomo extension to latest, changes include making extension usable with different matomo instances, api tracking is now optional and dataset graphs are included in the extension, opendata however still uses its own.

Update matomo extension

---

cdk/lib/monitoring-stack.ts

- For some reason Regexp matches were not supported, so changed to suffix check which may produce some false positives but no false negatives

AV-1959: Use suffix check instead of regexp

---

.github/workflows/test.yml
cdk/bin/opendata.ts
cdk/lib/ci-test-stack-props.ts
cdk/lib/ci-test-stack.ts
ckan/Dockerfile
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/resourcestatusplugin.py

Creates a new stack which has test bucket and a role which has access to the bucket.
Github Actions now use the role to generate temporary credentials which are injected to docker environment variables.
Replaces sed with python-dotenv for easier maintainability in Github actions script.
Supplies cloudstorage driver options to resourcestatus plugin for it to fetch tags.

AV-2067: create test bucket and role

---

drupal/modules/avoindata-explore/avoindata_explore.module
drupal/modules/avoindata-explore/src/Plugin/Block/ExternalBlock.php
drupal/modules/avoindata-explore/templates/avoindata_external_block.html.twig
drupal/modules/avoindata-header/templates/avoindata_header.html.twig
drupal/modules/avoindata-theme/config/install/block.block.avoindata_external.yml
opendata-assets/src/images/logo-suomifi.svg
opendata-assets/src/less/drupal/overrides.less
opendata-assets/src/less/navbars.less

Adds the following UI components:
Header has a new link:
Front page has a new block:
translations are still missing, well figure it out with technical writers.

AV-2061: Add links to suojattudata

---

docker/postgres/docker-entrypoint-initdb.d/00_init_db.sh

Will add manually to current rds instances, probably will not be needed for new rds instances since future drupal will automatically create this with postgres 13 when creating a new database.

AV-2055: Add pg_trgm extension to database as drupal 10 requires it

---

drupal/scripts/init_drupal.sh

The block that avoindata_infobox provides has not been in use in 4 years, this uninstalls the module from database so that it can be completely removed.

Uninstall avoindata_infobox

---

cdk/lib/ckan-stack.ts

resourcestatus expects an empty value for it use sessions fetching tags from aws. When driver_options is not defined, environ will input string "None" into it.

AV-2079: Fix resourcestatus causing an error

---

cdk/bin/opendata.ts
ckan/templates/ckan-uwsgi.ini.j2

Starts from 1 process and scales up to the max process count, which depends on the environment.

Use dynamic process scaling in uwsgi

---

drupal/modules/avoindata-hero/avoindata_hero.module
drupal/modules/avoindata-hero/src/Plugin/Form/HeroForm.php
drupal/modules/avoindata-hero/templates/avoindata_hero_form.html.twig

Language variables where removed in https://github.com/vrk-kpa/opendata/pull/1897, but they are actually required for urls to generate correctly, this should fix them without causing the original error.

AV-2084: Set language variable correctly

---

drupal/modules/avoindata-hero/avoindata_hero.module
drupal/modules/avoindata-hero/templates/avoindata_hero_form.html.twig

The form lost its definitions if variables were given, the language is available in the form itself as an attribute.

Fix hero search by supplying the language through the form and not the rendering block

---

opendata-assets/src/less/navbars.less

Bootstrap 3 purposefully removes outline on dropdowns, this has been fixed on newer versions, but this replicates the css for our uses for now.

AV-2090: Fix navbar focus on dropdowns

---

drupal/modules/avoindata-theme/templates/menu/vertical-menu-base-template.html.twig

- During guide mobile view development an unnecessary default collapse had been added to vertical menus. Removing it restores the footer links.

AV-2107: fix footer links by removing unnecessary default collapse

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/package/resource_read.html
cypress/e2e/dataset_resource_spec.js

Adds separate data updated and metadata updated field to the resource read UI based on ckan templates.
Add timestamps to the table so it doesn't just show a date in it.

AV-2105: Add data updated field to UI and add timestamps as well

---

cdk/bin/opendata.ts

Domains are global, we do not want to deploy relevant stacks multiple times.

Deploy domain stacks only to eu-west-1

---

cdk/lib/shield-stack.ts

StringList return a list with single string parameter which is comma delimited, CfnParameter return actual list.

Fix stringlist parameters returning a comma delimited list

---

opendata-assets/src/less/ckan/upstream-overrides.less
opendata-assets/src/less/components/additional-info.less
opendata-assets/src/less/components/tags.less

Aligns labels vertically:
Removes custom styling from table of tags, which might have been design error:
Fixes margins of tags which was invalid css and now they have actual margins:

AV-2171: Fix additional info table styling

---

ckan/cron/crontab

- `*` means every value, meaning these two tasks ran every minute on the given hour, change to `0` to run once

AV-2175: Avoid running background tasks every minute

---

cdk/bin/opendata.ts
cdk/lib/ckan-stack-props.ts
cdk/lib/ckan-stack.ts
cdk/test/ckan-stack.test.ts

Only enables data fetching in productions, not in use even in local environments by default.

AV-2006: Migrate prh tools and enable them production

---

cdk/lib/shield-stack.ts

`for .. in` for lists produces indexes, `for .. of` produces actual elements.

Fix syntax error in shield stack

---

docker/datapusher-plus/Dockerfile

Builds latest qsv from crates as musl builds have been failing for awhile https://github.com/jqnatividad/qsv/issues/1563.
Installs datapusher from zipped archive as releases have been slow, the repository can be changed once https://github.com/dathere/datapusher-plus/pull/133 has been merged.
uchardet is required as latest datapusher uses it to identify file encodings.

AV-2031: Update datapusher and qsv

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/tests/test_plugin.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/validators.py
ckan/ckanext/ckanext-ytp_main/test.ini

The fix itself is a simple one where empty strings are ignored from repeating text input lists. This mostly adds tests related to external urls but the fix works also for other repeating text inputs.

AV-2199: Fix deleting external urls

---

ckan/Dockerfile
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/plugin.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/tests/test_plugin.py
ckan/ckanext/ckanext-ytp_main/test.ini
ckan/src/ckan/patches/fix_use_default_schema_parameter.patch

There is a bug in ckan that doesn't handle boolean with parameter `use_default_schema`, it just uses default schema if the parameter exists in the api call.
Fixes the server error by removing schema from context on `group_list` call, as the schema in context is dataset schema which is totally wrong for group calls.

AV-2202: Fix server error in package_show api

---

cdk/lib/ckan-stack.ts

Uploading files to resources require access to datapusher and back.

AV-2006: Allow connections from cron container to datapusher and back

---

.github/workflows/open_prs.yml

Implemented a feature for https://github.com/vrk-kpa/fetch-open-prs, where repository input can be a list, so that every repository does not need a workflow to notify in zulip about the open prs and no need to configure the secret to every repository.

Add ckanext-matomo to open prs workflow

---

.github/workflows/open_prs.yml

If there are no open pull requests, the workflow was failing on empty message sending.

Do not try send zulip message if there are no open pull requests

---

cdk/bin/opendata.ts
cdk/lib/backup-stack-props.ts
cdk/lib/cluster-stack-props.ts
cdk/lib/common-stack-props.ts
cdk/lib/create-databases-and-users-props.ts
cdk/lib/ec-stack-props.ts
cdk/lib/efs-stack-props.ts
cdk/lib/elb-stack-props.ts
cdk/lib/env-stack-props.ts
cdk/lib/lambda-stack-props.ts
cdk/lib/lambda-stack.ts
cdk/lib/monitoring-stack-props.ts
cdk/lib/rds-stack-props.ts
cdk/lib/send-to-zulip-props.ts
cdk/lib/shield-stack-props.ts
cdk/test/cache-stack.test.ts
cdk/test/ckan-stack.test.ts
cdk/test/cluster-stack.test.ts
cdk/test/database-stack.test.ts
cdk/test/drupal-stack.test.ts
cdk/test/filesystem-stack.test.ts
cdk/test/load-balancer-stack.test.ts

`CommonStackProps` had properties which weren't needed in most stacks, this moves `environment` property to separate `EnvStackProps` and simplifies amount of properties in the stacks.
```mermaid
---
title: Old Props
---
classDiagram
class StackProps{
object env
}
class CommonStackProps{
EnvProps envProps
string environment
string fqdn
string secondaryFqdn
string domainName
string secondaryDomainName
}
class EnvProps {
string REGISTRY
string REPOSITORY
....
}
StackProps<|--CommonStackProps
EnvProps*--CommonStackProps
````
```mermaid
---
title: New Props
---
classDiagram
class StackProps{
object env
}
class CommonStackProps{
EnvProps envProps
string fqdn
string secondaryFqdn
string domainName
string secondaryDomainName
}
class EnvProps {
string REGISTRY
string REPOSITORY
....
}
class …
```

Refactor env props in cdk not to reference unneeded properties

---

.github/workflows/restart_beta_containers.yml
.github/workflows/restart_prod_containers.yml
cdk/lib/ckan-stack.ts
cdk/lib/drupal-stack.ts
cloudformation/github-actions-stack.yml

Add workflows for restarting services in different environments. Updates role policies to allow this and makes build role optional in template, it doesn't exist in dev account. Adds names to services for easier referral in workflow.

Add restart services workflows and necessary modifications

---

ckan/templates/production.ini.j2

CKAN 2.9.11 limited allowed query parsers by default and the spatial search failed. This adds the query parser used by ckanext-spatial to allowed list.

AV-2179: Allow frange query parser to fix spatial search

---

cypress/support/commands.js

The delete api page includes the api name in the sentence, this removes the question mark so that the page and modal are testing the same text.

Update flaky cypress test

---

cdk/bin/opendata.ts
cdk/lib/bypass-cdn-stack.ts
cdk/lib/load-balancer-stack.ts
cdk/lib/parameter-stack.ts
cdk/lib/shield-parameter-stack.ts
cdk/lib/shield-stack-props.ts
cdk/lib/shield-stack.ts
cloudformation/cloudfront.yml

Adds records for www subdomain in primary and alternate domains targeted to loadbalancer, requires deletion of old ones from cloudfront cloudformation template.
Removes firewall rules blocking access to loadbalancer from other than cloudfront.
Adds redirection from http to https in loadbalancer as it was done in cloudfront.
Creates parameter stack for waf parameters to eu-west-1 region.
Recreates shield stack to be in eu-west-1 region and binds it to loadbalancer.

AV-2238: Bypass cloudfront

---

cdk/lib/ckan-stack.ts
docker/docker-compose.yml

Container writes its contents into `/var/solr/data` instead.

AV-2240: Fix solr containers to mount volumes into correct paths

---

cdk/lib/ckan-stack.ts
docker/docker-compose.yml

`/var/solr/data` includes files from container so mounting efs volume in there doesn't work.

AV-2240: Test number 2 to fix solr volumes

---

ckan/cron/scripts/prh-clear.sh

busybox date does not have string parsing, this calculates tomorrows date using arithmetic operations.

AV-2242: fix cron script on last day of month on busybox

---

.github/workflows/check.yml
drupal/Dockerfile
drupal/composer.json
drupal/composer.lock
drupal/scripts/init_drupal.sh

Most changes are in lock file as `composer.json` version ranges permit upgrades. Updates the base image to match the drupal version and php as 8.1 image does not exist. 
Upgrades plugins in `composer.json`to recommeded versions and removes fontawesome_menu_icons as its not actually used anywhere.

AV-2273:  Upgrade drupal and its modules

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/templates/report/index.html
opendata-assets/src/less/components/reports.less

- Remove whitespace from between columns
- Fix ["height problem"](https://stackoverflow.com/questions/22310912/bootstrap-row-with-columns-of-different-height) using `inline-block` items 
Before
After

AV-2234: Fix report grid alignment

---

.github/workflows/test.yml
docker/README.md
opendata-assets/README.md

docker-compose v1 has been deprecated and removed, this replaces it with v2 which uses dashes instead of underscores in container names.

Fix CI docker compose

---

cdk/lib/web-stack.ts

CSP is creating a error as the other domain is missing from headers, also adds protocols to those and fixes one typo in variable.

Add sentry browser domain to csp headers

---

docker/datapusher-plus/Dockerfile

qsv had updated its cli, this has the required modifications and related pr https://github.com/dathere/datapusher-plus/pull/160

AV-2296: Fix datapusher compatability with qsv

---

doc/dcat-ap/template.html.j2
docker/nginx/www/ns/index.html

- Get Bootstrap CSS from CDN instead of Drupal
- Drupal static content depends on environment so it's not reliable

Get Bootstrap styles for DCAT-AP namespace page from CDN

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/cli.py

- Adding users to groups now requires username in context even with ignore_auth

AV-2320: Fix opendata-group add CLI command

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/dcat.py
doc/dcat-ap/model.yml
docker/nginx/www/ns/index.html

Adds collection type to dcat profile and updates namespace documentation

AV-2397: Add collection type to dcat profile

---

doc/dcat-ap/README.md
doc/dcat-ap/model.yml
docker/nginx/www/ns/index.html

collectionType belongs to Dataset, not Catalog

Move collectionType to correct place

---

cdk/lib/database-stack.ts

Doesn't change anything, it is version 14 but it has been default, easier to track changes when it's actually defined in code.

Define datastore db engine version

---

cdk/lib/database-stack.ts

Upgrades datastore db engine, allowing major updates needs to deployed separately before hand.

Upgrade datastore postgres engine to 16

---

cdk/bin/opendata.ts
cdk/lib/ci-test-stack-props.ts
cdk/lib/ci-test-stack.ts

Allow vrk-kpa/ckanext-cloudstorage to use the CI role.

Allow cloudstorage to use test role in aws

---

ckan/ckan-requirements.txt

Changelogs https://flask.palletsprojects.com/en/stable/changes/#version-1-1-4 contain only couple bug fixes, sentry sdk requires 1.1.4

Upgrade flask for minimum required by sentry

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/harvesters/syke_harvester.py

Syke harvester did not have validate packages feature which was implemented in ckan harverster in https://github.com/vrk-kpa/ckanext-harvest/commit/ec4c55c65d3e10b594984e275456b219d01c8959
without it, creating tags might fail on sql level and harvesting crashes or acts weirdly.

AV-2418: Add validate packages feature to syke harvester

---

drupal/Dockerfile
drupal/configurations/uploads.ini
drupal/scripts/init_drupal.sh
drupal/templates/services.yml.j2
drupal/templates/settings.php.j2

Fixes various errors and recommendentation from http://localhost/fi/admin/reports/status
Notable changes are refreshing `services.yml` and `settings.php` from drupal default ones to get the new settings to be present. The changes of the files are mostly from those default files.
Sets Samesite setting of session cookie to Strict as I don't remember we have a reason to have Lax in there?

Drupal settings maintenance

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/harvesters/syke_harvester.py

Datasets in syke have harvesting information in there https://ckan.ymparisto.fi/api/action/package_search which was harvested as is. But as solr queries assume to have our internal ids in them, harvest status page didn't list harvested datasets, this removes the information and as such replaces it with our own.

AV-2418: Remove harvested information about harvesting which broke solr queries

---

cdk/lib/ckan-stack.ts
cdk/lib/drupal-stack.ts

Moves smtp username from parameter store to secrets manager, for allowing it to be reread without running deployment.

AV-2319: Move smtp username to secrets

---

ckan/ckanext/ckanext-ytp_recommendation/ckanext/ytp_recommendation/plugin.py

Recommendation count fetching failing yields an internal server error. Default to zero recommendations instead.

Recommendation count fetch error should not break dataset show

---

.gitmodules
ckan/Dockerfile
ckan/templates/production.ini.j2

Replaces ckanext-qa fork with upstream repo, it hardly had any differences https://github.com/ckan/ckanext-qa/compare/master...vrk-kpa:ckanext-qa:master.
Otherwise update ckanext-qa to latest, adds qsv binary to container to handle sniffing of files.

AV-2000: ckanext-qa 2.10 & 2.11 support

---

ckan/templates/production.ini.j2

SVGs were limited by default due to XSS possibilities, this allows them in groups as we don't allow normal users to create groups.

AV-2429: Allow svgs in group images

---

ckan/Dockerfile

Sentry had errors that `file` is missing, this adds it to container.

Add 'file' to ckan container, ckanext-qa requires it

---

cdk/lib/load-balancer-stack.ts

30 days of logs are retained, but versions of those have been never removed, this will delete all expired versions after 30 days.

Delete versions of deleted log entries

---

.github/workflows/master.yml
.github/workflows/prod.yml

Tags images used in prod with `prod-` prefix, can be later used to clean old images for repositories.

AV-2434: Tag prod images

---

clamav/clamav-docker/src/app.py

`scan_output` has `ERROR` status items if something goes wrong during the scan. Handle these as errors instead of just marking the files safe.

AV-2187: Do not silently error and mark files as clean in case of errors

---

cloudformation/ecr-repository-stack.yml

Adds the following rules to ecr template:
1. Keeps the image tagged as latest (the one used on dev)
2. Keeps 3 latest images tagged with prefix `prod-`, the current one in use in prod and 2 others
3. Keeps any other image for a week.

AV-2343: Add expiry rules on ecr template

---

cdk/lib/clamav-scanner-stack.ts

Logging shows the clamav task fails when it tries to publish a message on teh provided SNS topic, grant publish privileges.

AV-2187: Allow clamav task to publish on the provided SNS topic

---

clamav/clamav-docker/src/app.py

After finding a virus the clamav task marks the file as infected and empties the s3 file content. This causes the bucket to issue a notification that the file has changed, prompting a second scan that overwrites the status as clean, since the file no longer contains the virus.
Zero-length files cannot have viruses, so we can safely just skip scanning them to avoid this.

AV-2187: Skip scanning empty files for viruses

---

cdk/lib/clamav-scan-props.ts
cdk/lib/clamav-scan.function.ts
cdk/lib/clamav-scan.ts
cdk/lib/clamav-scanner-stack.ts

- Create a security group for clamav containers that allows EFS traffic on port 2049
- Add root privileges for clamav containers to the clamav EFS volume

AV-2187: Add EFS privileges and open ports for it for clamav containers

---

clamav/clamav-docker/src/app.py

- `put_object_tagging` overwrites all tags, so infection information was scrubbed on the second run triggered by replacing infected objects with empty ones
- If the file was earlier marked as clean in CKAN, the marking would stick because the `malware` tag would be missing afterwards
- Same for if it was earlier marked as infected. The first value would stick.
- Fix by not updating object tags unless proceeding to run a scan

AV-2187: Fix infection information by not overwriting tagging for empty files

---

cdk/bin/opendata.ts
cdk/lib/ckan-stack.ts
cdk/lib/drupal-stack.ts
cdk/lib/efs-stack-props.ts
cdk/lib/filesystem-stack.ts
cdk/test/ckan-stack.test.ts
cdk/test/drupal-stack.test.ts
cdk/test/filesystem-stack.test.ts

CKAN and Drupal stack have migration efs mount which held the old data from ec2 era. The data has been migrated to the new efs volumes, so these can be removed from the stacks. Deploy probably fails due to dependecies between the stacks but i'll fix them if that happens.
Allows deleting the old efs completely.

AV-1536: Remove migration fs from stacks, allows deleting the old unencrypted efs

---

cdk/lib/ckan-stack.ts
docker/README.md
docker/docker-compose.yml
docker/nginx/Dockerfile
docker/solr/Dockerfile

Configures various healthcheck for docker containers, both local and in ecs. CDK defaults to container health check if its not defined so some of those were moved around.
Now all containers (except local mailhog, should be replaced) report healthy status.

AV-2440:  Configure docker healthchecks

---

cdk/lib/shield-stack.ts

Even though documentation says otherwise.

AV-2440: shield protection can only have one healthcheck

---

cdk/lib/shield-stack.ts

Since there can be only one health check on shield, this defines cloudwatch alarm on target response time and uses that as health check.

AV-2440: Second attempt on health check

---

ckan/ckanext/ckanext-ytp_main/ckanext/ytp/reports.py

- handle `ObjectNotFound` exceptions from `qa_package_openness_show` by disregarding such cases in openness score average calculations
- added type annotations and fixed various style issues

AV-2435: Handle ObjectNotFound exceptions in openness_score_avg

---

ckan/Dockerfile

Used alpine version has lost its support, this upgrades alpine and python 3.9 to latest. 
Also remove base image arg as automatic updates does not pick up the version from that.

Upgrade python and alpine versions, and move base image out of arg variable

---

.github/workflows/test.yml
ckan/Dockerfile
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/tests/test_plugin.py
ckan/ckanext/ckanext-ytp_main/test.ini
ckan/src/ckan/patches/fix_templatehelpers_plugin_order.patch

Fixes template helpers order with a patch to ckan core and adds tests.
Adds patch file to github actions test workflow as unit tests are run with ckan provided container, which requires said patch to fix bug in ckan core.

AV-2447: Fix Templatehelpers order

---

ckan/Dockerfile
ckan/src/ckan/patches/fix_server_error_on_group_pages.patch

Group and organization pages produce errors on sentry when there are invalid searches, CKAN has a fix for this on 2.11 onwards, this PR adds that fix to our environment.

Fix server error on invalid searches with ckan patch

---

.github/workflows/test.yml
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/tests/test_plugin.py
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/views_organization.py
ckan/ckanext/ckanext-ytp_main/test.ini

`render` only takes `extra_vars` parameter, deprecated args and kwargs arguments were removed.
Add various placeholder files for unit tests as these are created by asset build and unit tests don't really require functional front end, only that pages actually open.

Fix server error on deleted organization, extra arguments to render were deprecated and removed

---

.github/workflows/test.yml
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/resources/opendata/scripts/ytp_form.js
ckan/ckanext/ckanext-ytp_main/ckanext/ytp/resources/webassets.yml
opendata-assets/package-lock.json
opendata-assets/package.json

Sentry has constant errors from jstree, its not used in anywhere anymore as org hierarchy has been reimplemented years ago not to use jstree, so this removes it from our assets.

Remove jstree, it produces errors on clients
